# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'userswSunw.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_AdminSignIn(object):
    def setupUi(self, AdminSignIn):
        if AdminSignIn.objectName():
            AdminSignIn.setObjectName(u"AdminSignIn")
        AdminSignIn.resize(444, 308)
        palette = QPalette()
        brush = QBrush(QColor(157, 102, 18, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush2 = QBrush(QColor(120, 120, 120, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        AdminSignIn.setPalette(palette)
        AdminSignIn.setAutoFillBackground(True)
        self.centralwidget = QWidget(AdminSignIn)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 0, 621, 81))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.label_16.setPalette(palette1)
        self.label_16.setAutoFillBackground(True)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(-30, 10, 521, 41))
        palette2 = QPalette()
        brush4 = QBrush(QColor(255, 255, 127, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush1)
        brush5 = QBrush(QColor(255, 255, 191, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush5)
        brush6 = QBrush(QColor(127, 127, 63, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush6)
        brush7 = QBrush(QColor(170, 170, 84, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush7)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush3)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush5)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
        brush9 = QBrush(QColor(0, 0, 0, 128))
        brush9.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
        brush10 = QBrush(QColor(0, 0, 0, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
#endif
        self.label_9.setPalette(palette2)
        font = QFont()
        font.setFamily(u"Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setToolTipDuration(-4)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(150, 40, 171, 20))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.label_11.setPalette(palette3)
        font1 = QFont()
        font1.setPointSize(7)
        self.label_11.setFont(font1)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(90, -20, 91, 101))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.label_10.setPalette(palette4)
        font2 = QFont()
        font2.setFamily(u"Century Gothic")
        font2.setPointSize(28)
        font2.setBold(False)
        font2.setWeight(50)
        self.label_10.setFont(font2)
        self.label_10.setAutoFillBackground(False)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 70, 441, 351))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Base, brush1)
        brush12 = QBrush(QColor(159, 103, 18, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush12)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush12)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush12)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush12)
        self.label_14.setPalette(palette5)
        self.label_14.setAutoFillBackground(True)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 120, 71, 16))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.label_3.setPalette(palette6)
        font3 = QFont()
        font3.setFamily(u"Century Gothic")
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setWeight(75)
        self.label_3.setFont(font3)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 180, 161, 16))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.label_4.setPalette(palette7)
        self.label_4.setFont(font3)
        self.txtUser = QLineEdit(self.centralwidget)
        self.txtUser.setObjectName(u"txtUser")
        self.txtUser.setGeometry(QRect(110, 120, 291, 20))
        self.txtPass = QLineEdit(self.centralwidget)
        self.txtPass.setObjectName(u"txtPass")
        self.txtPass.setGeometry(QRect(150, 180, 251, 21))
        self.txtPass.setEchoMode(QLineEdit.Password)
        self.btnLogin = QPushButton(self.centralwidget)
        self.btnLogin.setObjectName(u"btnLogin")
        self.btnLogin.setGeometry(QRect(170, 240, 101, 41))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush12)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush12)
        palette8.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush12)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush12)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush12)
        palette8.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush12)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush12)
        palette8.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        self.btnLogin.setPalette(palette8)
        font4 = QFont()
        font4.setFamily(u"Century Gothic")
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.btnLogin.setFont(font4)
        self.btnLogin.setAutoFillBackground(True)
        AdminSignIn.setCentralWidget(self.centralwidget)
        self.label_14.raise_()
        self.label_16.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.label_10.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.txtUser.raise_()
        self.txtPass.raise_()
        self.btnLogin.raise_()
        self.statusbar = QStatusBar(AdminSignIn)
        self.statusbar.setObjectName(u"statusbar")
        AdminSignIn.setStatusBar(self.statusbar)

        self.retranslateUi(AdminSignIn)

        QMetaObject.connectSlotsByName(AdminSignIn)
    # setupUi

    def retranslateUi(self, AdminSignIn):
        AdminSignIn.setWindowTitle(QCoreApplication.translate("AdminSignIn", u"USER LOG-IN", None))
        self.label_16.setText("")
        self.label_9.setText(QCoreApplication.translate("AdminSignIn", u"H O T E L   D E L   L U N A ", None))
        self.label_11.setText(QCoreApplication.translate("AdminSignIn", u"A   P L A C E   L I K E    H O M E", None))
        self.label_10.setText(QCoreApplication.translate("AdminSignIn", u"O", None))
        self.label_14.setText("")
        self.label_3.setText(QCoreApplication.translate("AdminSignIn", u"USER :", None))
        self.label_4.setText(QCoreApplication.translate("AdminSignIn", u"PASSWORD :", None))
        self.btnLogin.setText(QCoreApplication.translate("AdminSignIn", u"LOG - IN", None))
    # retranslateUi

