# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'EDIT-ROOM-INFORMATIONLCSOxS.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_EditRoomInfo(object):
    def setupUi(self, EditRoomInfo):
        if EditRoomInfo.objectName():
            EditRoomInfo.setObjectName(u"EditRoomInfo")
        EditRoomInfo.resize(927, 619)
        self.buttonBox = QDialogButtonBox(EditRoomInfo)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(-120, 570, 681, 61))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Close|QDialogButtonBox.Save)
        self.label_2 = QLabel(EditRoomInfo)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 30, 791, 41))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 127, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush)
        brush2 = QBrush(QColor(255, 255, 191, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        brush3 = QBrush(QColor(127, 127, 63, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush3)
        brush4 = QBrush(QColor(170, 170, 84, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush4)
        brush5 = QBrush(QColor(0, 0, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        brush6 = QBrush(QColor(255, 255, 220, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush7 = QBrush(QColor(0, 0, 0, 128))
        brush7.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush5)
        brush8 = QBrush(QColor(0, 0, 0, 128))
        brush8.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush5)
        brush9 = QBrush(QColor(0, 0, 0, 128))
        brush9.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.label_2.setPalette(palette)
        font = QFont()
        font.setFamily(u"Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setToolTipDuration(-4)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(EditRoomInfo)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(100, 90, 351, 221))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush10 = QBrush(QColor(120, 120, 120, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox.setPalette(palette1)
        font1 = QFont()
        font1.setFamily(u"Century Gothic")
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setWeight(75)
        self.groupBox.setFont(font1)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 30, 181, 20))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_3.setPalette(palette2)
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(False)
        font2.setWeight(50)
        self.label_3.setFont(font2)
        self.roomAText = QTextBrowser(self.groupBox)
        self.roomAText.setObjectName(u"roomAText")
        self.roomAText.setGeometry(QRect(0, 60, 351, 161))
        self.roomAText.setUndoRedoEnabled(True)
        self.roomAText.setReadOnly(False)
        self.roomAText.setOverwriteMode(False)
        self.label = QLabel(EditRoomInfo)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(200, 0, 521, 41))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush5)
        brush12 = QBrush(QColor(0, 0, 0, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush5)
        brush13 = QBrush(QColor(0, 0, 0, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush13)
#endif
        self.label.setPalette(palette3)
        font3 = QFont()
        font3.setFamily(u"Century Gothic")
        font3.setPointSize(26)
        font3.setBold(True)
        font3.setWeight(75)
        self.label.setFont(font3)
        self.label.setToolTipDuration(-4)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(EditRoomInfo)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 0, 931, 621))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Base, brush)
        brush14 = QBrush(QColor(159, 103, 18, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        self.label_5.setPalette(palette4)
        self.label_5.setAutoFillBackground(True)
        self.label_7 = QLabel(EditRoomInfo)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 20, 881, 581))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Base, brush)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        self.label_7.setPalette(palette5)
        self.label_7.setAutoFillBackground(True)
        self.label_10 = QLabel(EditRoomInfo)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(390, 60, 171, 20))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_10.setPalette(palette6)
        font4 = QFont()
        font4.setPointSize(8)
        self.label_10.setFont(font4)
        self.groupBox_4 = QGroupBox(EditRoomInfo)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(100, 330, 351, 241))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox_4.setPalette(palette7)
        self.groupBox_4.setFont(font1)
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 30, 181, 20))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_4.setPalette(palette8)
        self.label_4.setFont(font2)
        self.roomBText = QTextBrowser(self.groupBox_4)
        self.roomBText.setObjectName(u"roomBText")
        self.roomBText.setGeometry(QRect(0, 60, 351, 181))
        self.roomBText.setUndoRedoEnabled(True)
        self.roomBText.setReadOnly(False)
        self.groupBox_6 = QGroupBox(EditRoomInfo)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(510, 90, 351, 221))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox_6.setPalette(palette9)
        self.groupBox_6.setFont(font1)
        self.label_6 = QLabel(self.groupBox_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 30, 181, 20))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_6.setPalette(palette10)
        self.label_6.setFont(font2)
        self.roomCText = QTextBrowser(self.groupBox_6)
        self.roomCText.setObjectName(u"roomCText")
        self.roomCText.setGeometry(QRect(0, 60, 351, 161))
        self.roomCText.setUndoRedoEnabled(True)
        self.roomCText.setReadOnly(False)
        self.roomCText.setOverwriteMode(False)
        self.groupBox_7 = QGroupBox(EditRoomInfo)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(510, 330, 351, 241))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox_7.setPalette(palette11)
        self.groupBox_7.setFont(font1)
        self.label_8 = QLabel(self.groupBox_7)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(100, 30, 181, 20))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_8.setPalette(palette12)
        self.label_8.setFont(font2)
        self.roomDText = QTextBrowser(self.groupBox_7)
        self.roomDText.setObjectName(u"roomDText")
        self.roomDText.setGeometry(QRect(0, 60, 351, 181))
        self.roomDText.setUndoRedoEnabled(True)
        self.roomDText.setReadOnly(False)
        self.label_9 = QLabel(EditRoomInfo)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(100, 310, 171, 16))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush14)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush14)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_9.setPalette(palette13)
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(False)
        font5.setWeight(50)
        self.label_9.setFont(font5)
        self.label_42 = QLabel(EditRoomInfo)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(100, 570, 171, 16))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush14)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush14)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_42.setPalette(palette14)
        self.label_42.setFont(font5)
        self.label_43 = QLabel(EditRoomInfo)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(750, 310, 171, 16))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush14)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush14)
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_43.setPalette(palette15)
        self.label_43.setFont(font5)
        self.label_44 = QLabel(EditRoomInfo)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(750, 570, 171, 16))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush14)
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush14)
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_44.setPalette(palette16)
        self.label_44.setFont(font5)
        self.label_5.raise_()
        self.label_7.raise_()
        self.buttonBox.raise_()
        self.label_2.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.label_10.raise_()
        self.groupBox_4.raise_()
        self.groupBox_6.raise_()
        self.groupBox_7.raise_()
        self.label_9.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.label_44.raise_()

        self.retranslateUi(EditRoomInfo)
        # self.buttonBox.accepted.connect(EditRoomInfo.accept)
        # self.buttonBox.rejected.connect(EditRoomInfo.reject)

        QMetaObject.connectSlotsByName(EditRoomInfo)
    # setupUi

    def retranslateUi(self, EditRoomInfo):
        EditRoomInfo.setWindowTitle(QCoreApplication.translate("EditRoomInfo", u"EditRoomInfo", None))
        self.label_2.setText(QCoreApplication.translate("EditRoomInfo", u"R  o  o  m     I  n  f  o  r  m  a  t  i  o  n", None))
        self.groupBox.setTitle(QCoreApplication.translate("EditRoomInfo", u"ROOM A - STANDARD NON - AC ", None))
        self.label_3.setText(QCoreApplication.translate("EditRoomInfo", u"* ROOM INCLUSIONS *", None))
        self.label.setText(QCoreApplication.translate("EditRoomInfo", u"H  O  T  E  L    D  E  L    L  U  N  A", None))
        self.label_5.setText("")
        self.label_7.setText("")
        self.label_10.setText(QCoreApplication.translate("EditRoomInfo", u"A   P L A C E   L I K E    H O M E", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("EditRoomInfo", u"ROOM B - STANDARD AC", None))
        self.label_4.setText(QCoreApplication.translate("EditRoomInfo", u"* ROOM INCLUSIONS *", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("EditRoomInfo", u"ROOM C - 3 BED NON - AC", None))
        self.label_6.setText(QCoreApplication.translate("EditRoomInfo", u"* ROOM INCLUSIONS *", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("EditRoomInfo", u"ROOM D - 3 BED AC", None))
        self.label_8.setText(QCoreApplication.translate("EditRoomInfo", u"* ROOM INCLUSIONS *", None))
        self.label_9.setText(QCoreApplication.translate("EditRoomInfo", u"[ PHP 3,500 / PAX ]", None))
        self.label_42.setText(QCoreApplication.translate("EditRoomInfo", u"[ PHP 4,000 / PAX ]", None))
        self.label_43.setText(QCoreApplication.translate("EditRoomInfo", u"[ PHP 4,500 / PAX ]", None))
        self.label_44.setText(QCoreApplication.translate("EditRoomInfo", u"[ PHP 5,000 / PAX ]", None))
    # retranslateUi

