# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'bookingYWtUmt.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_HotelBooking(object):
    def setupUi(self, HotelBooking):
        if HotelBooking.objectName():
            HotelBooking.setObjectName(u"HotelBooking")
        HotelBooking.resize(867, 627)
        self.label_15 = QLabel(HotelBooking)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 0, 1011, 61))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.label_15.setPalette(palette)
        self.label_15.setAutoFillBackground(True)
        self.label_9 = QLabel(HotelBooking)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(-110, 0, 521, 41))
        palette1 = QPalette()
        brush2 = QBrush(QColor(255, 255, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush)
        brush3 = QBrush(QColor(255, 255, 191, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(127, 127, 63, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(170, 170, 84, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush6 = QBrush(QColor(255, 255, 220, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush7 = QBrush(QColor(0, 0, 0, 128))
        brush7.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush8 = QBrush(QColor(0, 0, 0, 128))
        brush8.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush9 = QBrush(QColor(0, 0, 0, 128))
        brush9.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.label_9.setPalette(palette1)
        font = QFont()
        font.setFamily(u"Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setToolTipDuration(-4)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(HotelBooking)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, -20, 91, 101))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        brush10 = QBrush(QColor(120, 120, 120, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_10.setPalette(palette2)
        font1 = QFont()
        font1.setFamily(u"Century Gothic")
        font1.setPointSize(28)
        font1.setBold(False)
        font1.setWeight(50)
        self.label_10.setFont(font1)
        self.label_10.setAutoFillBackground(False)
        self.label_14 = QLabel(HotelBooking)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 60, 1021, 591))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Base, brush)
        brush11 = QBrush(QColor(157, 102, 18, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.label_14.setPalette(palette3)
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setWeight(75)
        self.label_14.setFont(font2)
        self.label_14.setAutoFillBackground(True)
        self.label_2 = QLabel(HotelBooking)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(430, 10, 521, 41))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush12 = QBrush(QColor(0, 0, 0, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush13 = QBrush(QColor(0, 0, 0, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush13)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush14 = QBrush(QColor(0, 0, 0, 128))
        brush14.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        self.label_2.setPalette(palette4)
        font3 = QFont()
        font3.setFamily(u"Century Gothic")
        font3.setPointSize(14)
        font3.setBold(False)
        font3.setWeight(50)
        self.label_2.setFont(font3)
        self.label_2.setToolTipDuration(-4)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.line_3 = QFrame(HotelBooking)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(810, 20, 21, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(HotelBooking)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(810, 10, 21, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(HotelBooking)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(810, 30, 21, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.groupBox = QGroupBox(HotelBooking)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 70, 411, 201))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox.setPalette(palette5)
        font4 = QFont()
        font4.setFamily(u"Century Gothic")
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.groupBox.setFont(font4)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 40, 91, 19))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_3.setPalette(palette6)
        font5 = QFont()
        font5.setFamily(u"Century Gothic")
        font5.setPointSize(10)
        self.label_3.setFont(font5)
        self.txtName = QLineEdit(self.groupBox)
        self.txtName.setObjectName(u"txtName")
        self.txtName.setGeometry(QRect(90, 40, 301, 21))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 160, 141, 19))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_7.setPalette(palette7)
        self.label_7.setFont(font5)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 120, 141, 19))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_5.setPalette(palette8)
        self.label_5.setFont(font5)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 80, 71, 19))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_4.setPalette(palette9)
        self.label_4.setFont(font5)
        self.txtAddress = QLineEdit(self.groupBox)
        self.txtAddress.setObjectName(u"txtAddress")
        self.txtAddress.setGeometry(QRect(100, 80, 291, 21))
        self.txtContact = QLineEdit(self.groupBox)
        self.txtContact.setObjectName(u"txtContact")
        self.txtContact.setGeometry(QRect(160, 120, 231, 21))
        self.txtPax = QLineEdit(self.groupBox)
        self.txtPax.setObjectName(u"txtPax")
        self.txtPax.setGeometry(QRect(160, 160, 231, 21))
        self.label_11 = QLabel(HotelBooking)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(70, 30, 171, 20))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_11.setPalette(palette10)
        font6 = QFont()
        font6.setPointSize(7)
        self.label_11.setFont(font6)
        self.groupBox_2 = QGroupBox(HotelBooking)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(440, 70, 411, 191))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox_2.setPalette(palette11)
        self.groupBox_2.setFont(font4)
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 30, 111, 17))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Light, brush)
        palette12.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette12.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette12.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush15 = QBrush(QColor(0, 0, 0, 128))
        brush15.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Active, QPalette.PlaceholderText, brush15)
#endif
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette12.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush16 = QBrush(QColor(0, 0, 0, 128))
        brush16.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush16)
#endif
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette12.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette12.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush17 = QBrush(QColor(0, 0, 0, 128))
        brush17.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush17)
#endif
        self.label_6.setPalette(palette12)
        self.label_6.setFont(font4)
        self.label_6.setToolTipDuration(-4)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.deIn = QDateEdit(self.groupBox_2)
        self.deIn.setObjectName(u"deIn")
        self.deIn.setGeometry(QRect(160, 30, 161, 20))
        font7 = QFont()
        font7.setPointSize(10)
        font7.setBold(False)
        font7.setWeight(50)
        self.deIn.setFont(font7)
        self.teIn = QTimeEdit(self.groupBox_2)
        self.teIn.setObjectName(u"teIn")
        self.teIn.setGeometry(QRect(160, 60, 118, 22))
        self.teIn.setFont(font7)
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 60, 111, 17))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Light, brush)
        palette13.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette13.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette13.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette13.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette13.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush18 = QBrush(QColor(0, 0, 0, 128))
        brush18.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Active, QPalette.PlaceholderText, brush18)
#endif
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette13.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette13.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush19 = QBrush(QColor(0, 0, 0, 128))
        brush19.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush19)
#endif
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette13.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush20 = QBrush(QColor(0, 0, 0, 128))
        brush20.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush20)
#endif
        self.label_17.setPalette(palette13)
        self.label_17.setFont(font4)
        self.label_17.setToolTipDuration(-4)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.groupBox_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 110, 131, 17))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Light, brush)
        palette14.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette14.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette14.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette14.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette14.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush21 = QBrush(QColor(0, 0, 0, 128))
        brush21.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Active, QPalette.PlaceholderText, brush21)
#endif
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette14.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette14.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush22 = QBrush(QColor(0, 0, 0, 128))
        brush22.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush22)
#endif
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette14.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette14.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush23 = QBrush(QColor(0, 0, 0, 128))
        brush23.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush23)
#endif
        self.label_18.setPalette(palette14)
        self.label_18.setFont(font4)
        self.label_18.setToolTipDuration(-4)
        self.label_18.setAutoFillBackground(False)
        self.label_18.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(self.groupBox_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 140, 131, 17))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Light, brush)
        palette15.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette15.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette15.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette15.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette15.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush24 = QBrush(QColor(0, 0, 0, 128))
        brush24.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Active, QPalette.PlaceholderText, brush24)
#endif
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette15.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette15.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette15.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush25 = QBrush(QColor(0, 0, 0, 128))
        brush25.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush25)
#endif
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette15.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette15.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette15.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush26 = QBrush(QColor(0, 0, 0, 128))
        brush26.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush26)
#endif
        self.label_19.setPalette(palette15)
        self.label_19.setFont(font4)
        self.label_19.setToolTipDuration(-4)
        self.label_19.setAutoFillBackground(False)
        self.label_19.setAlignment(Qt.AlignCenter)
        self.deOut = QDateEdit(self.groupBox_2)
        self.deOut.setObjectName(u"deOut")
        self.deOut.setGeometry(QRect(160, 110, 161, 20))
        self.deOut.setFont(font7)
        self.teOut = QTimeEdit(self.groupBox_2)
        self.teOut.setObjectName(u"teOut")
        self.teOut.setGeometry(QRect(160, 140, 118, 22))
        self.teOut.setFont(font7)
        self.groupBox_3 = QGroupBox(HotelBooking)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(440, 270, 411, 221))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox_3.setPalette(palette16)
        self.groupBox_3.setFont(font4)
        self.cbBar = QCheckBox(self.groupBox_3)
        self.cbBar.setObjectName(u"cbBar")
        self.cbBar.setGeometry(QRect(40, 60, 43, 21))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbBar.setPalette(palette17)
        self.cbBar.setFont(font4)
        self.cbPool = QCheckBox(self.groupBox_3)
        self.cbPool.setObjectName(u"cbPool")
        self.cbPool.setGeometry(QRect(40, 30, 52, 21))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbPool.setPalette(palette18)
        self.cbPool.setFont(font4)
        self.cbGym = QCheckBox(self.groupBox_3)
        self.cbGym.setObjectName(u"cbGym")
        self.cbGym.setGeometry(QRect(40, 180, 53, 21))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbGym.setPalette(palette19)
        self.cbGym.setFont(font4)
        self.cbSpa = QCheckBox(self.groupBox_3)
        self.cbSpa.setObjectName(u"cbSpa")
        self.cbSpa.setGeometry(QRect(40, 120, 50, 21))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbSpa.setPalette(palette20)
        self.cbSpa.setFont(font4)
        self.cbLibrary = QCheckBox(self.groupBox_3)
        self.cbLibrary.setObjectName(u"cbLibrary")
        self.cbLibrary.setGeometry(QRect(40, 150, 81, 21))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbLibrary.setPalette(palette21)
        self.cbLibrary.setFont(font4)
        self.cbA = QCheckBox(self.groupBox_3)
        self.cbA.setObjectName(u"cbA")
        self.cbA.setGeometry(QRect(160, 30, 181, 21))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbA.setPalette(palette22)
        self.cbA.setFont(font4)
        self.cbB = QCheckBox(self.groupBox_3)
        self.cbB.setObjectName(u"cbB")
        self.cbB.setGeometry(QRect(160, 60, 191, 21))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbB.setPalette(palette23)
        self.cbB.setFont(font4)
        self.cbC = QCheckBox(self.groupBox_3)
        self.cbC.setObjectName(u"cbC")
        self.cbC.setGeometry(QRect(160, 90, 211, 21))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbC.setPalette(palette24)
        self.cbC.setFont(font4)
        self.cbJakuzzi = QCheckBox(self.groupBox_3)
        self.cbJakuzzi.setObjectName(u"cbJakuzzi")
        self.cbJakuzzi.setGeometry(QRect(40, 90, 81, 21))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbJakuzzi.setPalette(palette25)
        self.cbJakuzzi.setFont(font4)
        self.cbD = QCheckBox(self.groupBox_3)
        self.cbD.setObjectName(u"cbD")
        self.cbD.setGeometry(QRect(160, 120, 211, 21))
        palette26 = QPalette()
        palette26.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette26.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbD.setPalette(palette26)
        self.cbD.setFont(font4)
        self.cbE = QCheckBox(self.groupBox_3)
        self.cbE.setObjectName(u"cbE")
        self.cbE.setGeometry(QRect(160, 150, 211, 21))
        palette27 = QPalette()
        palette27.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette27.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette27.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbE.setPalette(palette27)
        self.cbE.setFont(font4)
        self.cbF = QCheckBox(self.groupBox_3)
        self.cbF.setObjectName(u"cbF")
        self.cbF.setGeometry(QRect(160, 180, 211, 21))
        palette28 = QPalette()
        palette28.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette28.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette28.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.cbF.setPalette(palette28)
        self.cbF.setFont(font4)
        self.groupBox_4 = QGroupBox(HotelBooking)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 270, 411, 321))
        palette29 = QPalette()
        palette29.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette29.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette29.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox_4.setPalette(palette29)
        self.groupBox_4.setFont(font4)
        self.label_24 = QLabel(self.groupBox_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 30, 261, 21))
        palette30 = QPalette()
        palette30.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette30.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette30.setBrush(QPalette.Active, QPalette.Light, brush)
        palette30.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette30.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette30.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette30.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette30.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette30.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette30.setBrush(QPalette.Active, QPalette.Base, brush)
        palette30.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette30.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette30.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette30.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette30.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush27 = QBrush(QColor(0, 0, 0, 128))
        brush27.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette30.setBrush(QPalette.Active, QPalette.PlaceholderText, brush27)
#endif
        palette30.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette30.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette30.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette30.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette30.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette30.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette30.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette30.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette30.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette30.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette30.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette30.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette30.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette30.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette30.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush28 = QBrush(QColor(0, 0, 0, 128))
        brush28.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette30.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush28)
#endif
        palette30.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette30.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette30.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette30.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette30.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette30.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette30.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette30.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette30.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette30.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette30.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette30.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette30.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette30.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette30.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush29 = QBrush(QColor(0, 0, 0, 128))
        brush29.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette30.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush29)
#endif
        self.label_24.setPalette(palette30)
        self.label_24.setFont(font4)
        self.label_24.setToolTipDuration(-4)
        self.label_24.setAutoFillBackground(False)
        self.label_24.setAlignment(Qt.AlignCenter)
        self.label_26 = QLabel(self.groupBox_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(80, 70, 111, 21))
        palette31 = QPalette()
        palette31.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette31.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette31.setBrush(QPalette.Active, QPalette.Light, brush)
        palette31.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette31.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette31.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette31.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette31.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette31.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette31.setBrush(QPalette.Active, QPalette.Base, brush)
        palette31.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette31.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette31.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette31.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette31.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush30 = QBrush(QColor(0, 0, 0, 128))
        brush30.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette31.setBrush(QPalette.Active, QPalette.PlaceholderText, brush30)
#endif
        palette31.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette31.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette31.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette31.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette31.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette31.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette31.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette31.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette31.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette31.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette31.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette31.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette31.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette31.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette31.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush31 = QBrush(QColor(0, 0, 0, 128))
        brush31.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette31.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush31)
#endif
        palette31.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette31.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette31.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette31.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette31.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette31.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette31.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette31.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette31.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette31.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette31.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette31.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette31.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette31.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette31.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush32 = QBrush(QColor(0, 0, 0, 128))
        brush32.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette31.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush32)
#endif
        self.label_26.setPalette(palette31)
        font8 = QFont()
        font8.setFamily(u"Century Gothic")
        font8.setPointSize(9)
        font8.setBold(False)
        font8.setWeight(50)
        self.label_26.setFont(font8)
        self.label_26.setToolTipDuration(-4)
        self.label_26.setAutoFillBackground(False)
        self.label_26.setAlignment(Qt.AlignCenter)
        self.cmbA = QComboBox(self.groupBox_4)
        self.cmbA.setObjectName(u"cmbA")
        self.cmbA.setGeometry(QRect(60, 50, 151, 22))
        self.rbA = QRadioButton(self.groupBox_4)
        self.rbA.setObjectName(u"rbA")
        self.rbA.setGeometry(QRect(240, 50, 171, 17))
        palette32 = QPalette()
        palette32.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette32.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette32.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.rbA.setPalette(palette32)
        self.label_25 = QLabel(self.groupBox_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(0, 100, 261, 21))
        palette33 = QPalette()
        palette33.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette33.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette33.setBrush(QPalette.Active, QPalette.Light, brush)
        palette33.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette33.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette33.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette33.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette33.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette33.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette33.setBrush(QPalette.Active, QPalette.Base, brush)
        palette33.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette33.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette33.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette33.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette33.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush33 = QBrush(QColor(0, 0, 0, 128))
        brush33.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette33.setBrush(QPalette.Active, QPalette.PlaceholderText, brush33)
#endif
        palette33.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette33.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette33.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette33.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette33.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette33.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette33.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette33.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette33.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette33.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette33.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette33.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette33.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette33.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette33.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush34 = QBrush(QColor(0, 0, 0, 128))
        brush34.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette33.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush34)
#endif
        palette33.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette33.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette33.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette33.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette33.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette33.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette33.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette33.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette33.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette33.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette33.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette33.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette33.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette33.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette33.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush35 = QBrush(QColor(0, 0, 0, 128))
        brush35.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette33.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush35)
#endif
        self.label_25.setPalette(palette33)
        self.label_25.setFont(font4)
        self.label_25.setToolTipDuration(-4)
        self.label_25.setAutoFillBackground(False)
        self.label_25.setAlignment(Qt.AlignCenter)
        self.cmbB = QComboBox(self.groupBox_4)
        self.cmbB.setObjectName(u"cmbB")
        self.cmbB.setGeometry(QRect(60, 120, 151, 22))
        self.label_27 = QLabel(self.groupBox_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(80, 140, 111, 21))
        palette34 = QPalette()
        palette34.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette34.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette34.setBrush(QPalette.Active, QPalette.Light, brush)
        palette34.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette34.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette34.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette34.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette34.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette34.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette34.setBrush(QPalette.Active, QPalette.Base, brush)
        palette34.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette34.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette34.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette34.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette34.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush36 = QBrush(QColor(0, 0, 0, 128))
        brush36.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette34.setBrush(QPalette.Active, QPalette.PlaceholderText, brush36)
#endif
        palette34.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette34.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette34.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette34.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette34.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette34.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette34.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette34.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette34.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette34.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette34.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette34.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette34.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette34.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette34.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush37 = QBrush(QColor(0, 0, 0, 128))
        brush37.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette34.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush37)
#endif
        palette34.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette34.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette34.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette34.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette34.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette34.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette34.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette34.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette34.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette34.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette34.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette34.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette34.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette34.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette34.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush38 = QBrush(QColor(0, 0, 0, 128))
        brush38.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette34.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush38)
#endif
        self.label_27.setPalette(palette34)
        self.label_27.setFont(font8)
        self.label_27.setToolTipDuration(-4)
        self.label_27.setAutoFillBackground(False)
        self.label_27.setAlignment(Qt.AlignCenter)
        self.label_28 = QLabel(self.groupBox_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 170, 261, 21))
        palette35 = QPalette()
        palette35.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette35.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette35.setBrush(QPalette.Active, QPalette.Light, brush)
        palette35.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette35.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette35.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette35.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette35.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette35.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette35.setBrush(QPalette.Active, QPalette.Base, brush)
        palette35.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette35.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette35.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette35.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette35.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush39 = QBrush(QColor(0, 0, 0, 128))
        brush39.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette35.setBrush(QPalette.Active, QPalette.PlaceholderText, brush39)
#endif
        palette35.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette35.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette35.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette35.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette35.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette35.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette35.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette35.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette35.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette35.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette35.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette35.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette35.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette35.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette35.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush40 = QBrush(QColor(0, 0, 0, 128))
        brush40.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette35.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush40)
#endif
        palette35.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette35.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette35.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette35.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette35.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette35.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette35.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette35.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette35.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette35.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette35.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette35.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette35.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette35.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette35.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush41 = QBrush(QColor(0, 0, 0, 128))
        brush41.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette35.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush41)
#endif
        self.label_28.setPalette(palette35)
        self.label_28.setFont(font4)
        self.label_28.setToolTipDuration(-4)
        self.label_28.setAutoFillBackground(False)
        self.label_28.setAlignment(Qt.AlignCenter)
        self.cmbC = QComboBox(self.groupBox_4)
        self.cmbC.setObjectName(u"cmbC")
        self.cmbC.setGeometry(QRect(60, 190, 151, 22))
        self.label_29 = QLabel(self.groupBox_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(80, 210, 111, 21))
        palette36 = QPalette()
        palette36.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette36.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette36.setBrush(QPalette.Active, QPalette.Light, brush)
        palette36.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette36.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette36.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette36.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette36.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette36.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette36.setBrush(QPalette.Active, QPalette.Base, brush)
        palette36.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette36.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette36.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette36.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette36.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush42 = QBrush(QColor(0, 0, 0, 128))
        brush42.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette36.setBrush(QPalette.Active, QPalette.PlaceholderText, brush42)
#endif
        palette36.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette36.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette36.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette36.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette36.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette36.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette36.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette36.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette36.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette36.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette36.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette36.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette36.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette36.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette36.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush43 = QBrush(QColor(0, 0, 0, 128))
        brush43.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette36.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush43)
#endif
        palette36.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette36.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette36.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette36.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette36.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette36.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette36.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette36.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette36.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette36.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette36.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette36.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette36.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette36.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette36.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush44 = QBrush(QColor(0, 0, 0, 128))
        brush44.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette36.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush44)
#endif
        self.label_29.setPalette(palette36)
        self.label_29.setFont(font8)
        self.label_29.setToolTipDuration(-4)
        self.label_29.setAutoFillBackground(False)
        self.label_29.setAlignment(Qt.AlignCenter)
        self.label_30 = QLabel(self.groupBox_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 240, 261, 21))
        palette37 = QPalette()
        palette37.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette37.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette37.setBrush(QPalette.Active, QPalette.Light, brush)
        palette37.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette37.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette37.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette37.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette37.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette37.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette37.setBrush(QPalette.Active, QPalette.Base, brush)
        palette37.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette37.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette37.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette37.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette37.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush45 = QBrush(QColor(0, 0, 0, 128))
        brush45.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette37.setBrush(QPalette.Active, QPalette.PlaceholderText, brush45)
#endif
        palette37.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette37.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette37.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette37.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette37.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette37.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette37.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette37.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette37.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette37.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette37.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette37.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette37.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette37.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette37.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush46 = QBrush(QColor(0, 0, 0, 128))
        brush46.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette37.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush46)
#endif
        palette37.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette37.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette37.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette37.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette37.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette37.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette37.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette37.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette37.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette37.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette37.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette37.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette37.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette37.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette37.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush47 = QBrush(QColor(0, 0, 0, 128))
        brush47.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette37.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush47)
#endif
        self.label_30.setPalette(palette37)
        self.label_30.setFont(font4)
        self.label_30.setToolTipDuration(-4)
        self.label_30.setAutoFillBackground(False)
        self.label_30.setAlignment(Qt.AlignCenter)
        self.cmbD = QComboBox(self.groupBox_4)
        self.cmbD.setObjectName(u"cmbD")
        self.cmbD.setGeometry(QRect(60, 260, 151, 22))
        self.label_31 = QLabel(self.groupBox_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(80, 280, 111, 21))
        palette38 = QPalette()
        palette38.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette38.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette38.setBrush(QPalette.Active, QPalette.Light, brush)
        palette38.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette38.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette38.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette38.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette38.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette38.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette38.setBrush(QPalette.Active, QPalette.Base, brush)
        palette38.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette38.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette38.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette38.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette38.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush48 = QBrush(QColor(0, 0, 0, 128))
        brush48.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette38.setBrush(QPalette.Active, QPalette.PlaceholderText, brush48)
#endif
        palette38.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette38.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette38.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette38.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette38.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette38.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette38.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette38.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette38.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette38.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette38.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette38.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette38.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette38.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette38.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush49 = QBrush(QColor(0, 0, 0, 128))
        brush49.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette38.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush49)
#endif
        palette38.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette38.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette38.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette38.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette38.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette38.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette38.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette38.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette38.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette38.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette38.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette38.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette38.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette38.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette38.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush50 = QBrush(QColor(0, 0, 0, 128))
        brush50.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette38.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush50)
#endif
        self.label_31.setPalette(palette38)
        self.label_31.setFont(font8)
        self.label_31.setToolTipDuration(-4)
        self.label_31.setAutoFillBackground(False)
        self.label_31.setAlignment(Qt.AlignCenter)
        self.rbB = QRadioButton(self.groupBox_4)
        self.rbB.setObjectName(u"rbB")
        self.rbB.setGeometry(QRect(240, 120, 171, 17))
        palette39 = QPalette()
        palette39.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette39.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette39.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.rbB.setPalette(palette39)
        self.rbC = QRadioButton(self.groupBox_4)
        self.rbC.setObjectName(u"rbC")
        self.rbC.setGeometry(QRect(240, 190, 171, 17))
        palette40 = QPalette()
        palette40.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette40.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette40.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.rbC.setPalette(palette40)
        self.rbD = QRadioButton(self.groupBox_4)
        self.rbD.setObjectName(u"rbD")
        self.rbD.setGeometry(QRect(240, 260, 171, 17))
        palette41 = QPalette()
        palette41.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette41.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette41.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.rbD.setPalette(palette41)
        self.buttonBox = QDialogButtonBox(HotelBooking)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(560, 550, 191, 41))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        palette42 = QPalette()
        brush51 = QBrush(QColor(15, 1, 1, 255))
        brush51.setStyle(Qt.SolidPattern)
        palette42.setBrush(QPalette.Active, QPalette.Button, brush51)
        palette42.setBrush(QPalette.Active, QPalette.ButtonText, brush11)
        palette42.setBrush(QPalette.Inactive, QPalette.Button, brush51)
        palette42.setBrush(QPalette.Inactive, QPalette.ButtonText, brush11)
        palette42.setBrush(QPalette.Disabled, QPalette.Button, brush51)
        palette42.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        self.buttonBox.setPalette(palette42)
        self.buttonBox.setFont(font4)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.SaveAll)
        self.label_32 = QLabel(HotelBooking)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(210, 600, 531, 21))
        palette43 = QPalette()
        palette43.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette43.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette43.setBrush(QPalette.Active, QPalette.Light, brush)
        palette43.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette43.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette43.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette43.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette43.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette43.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette43.setBrush(QPalette.Active, QPalette.Base, brush)
        palette43.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette43.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette43.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette43.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette43.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush52 = QBrush(QColor(0, 0, 0, 128))
        brush52.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette43.setBrush(QPalette.Active, QPalette.PlaceholderText, brush52)
#endif
        palette43.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette43.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette43.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette43.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette43.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette43.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette43.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette43.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette43.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette43.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette43.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette43.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette43.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette43.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette43.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush53 = QBrush(QColor(0, 0, 0, 128))
        brush53.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette43.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush53)
#endif
        palette43.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette43.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette43.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette43.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette43.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette43.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette43.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette43.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette43.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette43.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette43.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette43.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette43.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette43.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette43.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush54 = QBrush(QColor(0, 0, 0, 128))
        brush54.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette43.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush54)
#endif
        self.label_32.setPalette(palette43)
        font9 = QFont()
        font9.setFamily(u"Century Gothic")
        font9.setPointSize(8)
        font9.setBold(False)
        font9.setWeight(50)
        self.label_32.setFont(font9)
        self.label_32.setToolTipDuration(-4)
        self.label_32.setAutoFillBackground(False)
        self.label_32.setAlignment(Qt.AlignCenter)
        self.label_33 = QLabel(HotelBooking)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(390, 520, 531, 21))
        palette44 = QPalette()
        palette44.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette44.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette44.setBrush(QPalette.Active, QPalette.Light, brush)
        palette44.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette44.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette44.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette44.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette44.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette44.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette44.setBrush(QPalette.Active, QPalette.Base, brush)
        palette44.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette44.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette44.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette44.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette44.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush55 = QBrush(QColor(0, 0, 0, 128))
        brush55.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette44.setBrush(QPalette.Active, QPalette.PlaceholderText, brush55)
#endif
        palette44.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette44.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette44.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette44.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette44.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette44.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette44.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette44.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette44.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette44.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette44.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette44.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette44.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette44.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette44.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush56 = QBrush(QColor(0, 0, 0, 128))
        brush56.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette44.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush56)
#endif
        palette44.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette44.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette44.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette44.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette44.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette44.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette44.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette44.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette44.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette44.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette44.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette44.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette44.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette44.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette44.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush57 = QBrush(QColor(0, 0, 0, 128))
        brush57.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette44.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush57)
#endif
        self.label_33.setPalette(palette44)
        self.label_33.setFont(font9)
        self.label_33.setToolTipDuration(-4)
        self.label_33.setAutoFillBackground(False)
        self.label_33.setAlignment(Qt.AlignCenter)

        self.retranslateUi(HotelBooking)

        QMetaObject.connectSlotsByName(HotelBooking)
    # setupUi

    def retranslateUi(self, HotelBooking):
        HotelBooking.setWindowTitle(QCoreApplication.translate("HotelBooking", u"HotelBooking", None))
        self.label_15.setText("")
        self.label_9.setText(QCoreApplication.translate("HotelBooking", u"H O T E L   D E L   L U N A ", None))
        self.label_10.setText(QCoreApplication.translate("HotelBooking", u"O", None))
        self.label_14.setText("")
        self.label_2.setText(QCoreApplication.translate("HotelBooking", u"H o t e l   B o o k i n g", None))
        self.groupBox.setTitle(QCoreApplication.translate("HotelBooking", u"PERSONAL INFORMATION", None))
        self.label_3.setText(QCoreApplication.translate("HotelBooking", u"Name :", None))
        self.label_7.setText(QCoreApplication.translate("HotelBooking", u"Number of Pax :", None))
        self.label_5.setText(QCoreApplication.translate("HotelBooking", u"Contact Number :", None))
        self.label_4.setText(QCoreApplication.translate("HotelBooking", u"Address :", None))
        self.label_11.setText(QCoreApplication.translate("HotelBooking", u"A   P L A C E   L I K E    H O M E", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("HotelBooking", u"TIME AND DATE", None))
        self.label_6.setText(QCoreApplication.translate("HotelBooking", u"Check-In Date  :", None))
        self.label_17.setText(QCoreApplication.translate("HotelBooking", u"Check-In Time  :", None))
        self.label_18.setText(QCoreApplication.translate("HotelBooking", u"Check-Out Date  :", None))
        self.label_19.setText(QCoreApplication.translate("HotelBooking", u"Check-Out Time  :", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("HotelBooking", u"Amenities", None))
        self.cbBar.setText(QCoreApplication.translate("HotelBooking", u"Bar", None))
        self.cbPool.setText(QCoreApplication.translate("HotelBooking", u"Pool", None))
        self.cbGym.setText(QCoreApplication.translate("HotelBooking", u"Gym", None))
        self.cbSpa.setText(QCoreApplication.translate("HotelBooking", u"Spa", None))
        self.cbLibrary.setText(QCoreApplication.translate("HotelBooking", u"Library", None))
        self.cbA.setText(QCoreApplication.translate("HotelBooking", u"Buffet A - SEAFOODS", None))
        self.cbB.setText(QCoreApplication.translate("HotelBooking", u"Buffet B - PINOY FOOD", None))
        self.cbC.setText(QCoreApplication.translate("HotelBooking", u"Buffet C - KOREAN FOOD", None))
        self.cbJakuzzi.setText(QCoreApplication.translate("HotelBooking", u"Jakuzzi", None))
        self.cbD.setText(QCoreApplication.translate("HotelBooking", u"Buffet D - CHINESE FOOD", None))
        self.cbE.setText(QCoreApplication.translate("HotelBooking", u"Buffet E - MEXICAN FOOD", None))
        self.cbF.setText(QCoreApplication.translate("HotelBooking", u"Buffet F - ITALIAN CUISINE", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("HotelBooking", u"Room Types", None))
        self.label_24.setText(QCoreApplication.translate("HotelBooking", u"ROOM A - Standard Non - AC", None))
        self.label_26.setText(QCoreApplication.translate("HotelBooking", u"Available Rooms", None))
        self.rbA.setText(QCoreApplication.translate("HotelBooking", u"[A] Reserve a slot ", None))
        self.label_25.setText(QCoreApplication.translate("HotelBooking", u"ROOM B - Standard AC", None))
        self.label_27.setText(QCoreApplication.translate("HotelBooking", u"Available Rooms", None))
        self.label_28.setText(QCoreApplication.translate("HotelBooking", u"ROOM C - 3 Bed Non - AC", None))
        self.label_29.setText(QCoreApplication.translate("HotelBooking", u"Available Rooms", None))
        self.label_30.setText(QCoreApplication.translate("HotelBooking", u"ROOM D - 3 Bed AC", None))
        self.label_31.setText(QCoreApplication.translate("HotelBooking", u"Available Rooms", None))
        self.rbB.setText(QCoreApplication.translate("HotelBooking", u"[B] Reserve a slot ", None))
        self.rbC.setText(QCoreApplication.translate("HotelBooking", u"[C] Reserve a slot", None))
        self.rbD.setText(QCoreApplication.translate("HotelBooking", u"[D] Reserve a slot", None))
        self.label_32.setText(QCoreApplication.translate("HotelBooking", u"NOTE: Rooms are strictly for reservation. First come, first serve! There are limited slot, BOOK NOW!", None))
        self.label_33.setText(QCoreApplication.translate("HotelBooking", u"KINDLY CHECK ALL THE GIVEN INFORMATION BEFORE PROCEEDING.", None))
    # retranslateUi

