# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'inventorylETjqI.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_RoomInventory(object):
    def setupUi(self, RoomInventory):
        if RoomInventory.objectName():
            RoomInventory.setObjectName(u"RoomInventory")
        RoomInventory.resize(861, 559)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(157, 102, 18, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        RoomInventory.setPalette(palette)
        RoomInventory.setAutoFillBackground(True)
        self.centralwidget = QWidget(RoomInventory)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 0, 1011, 61))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Base, brush)
        brush2 = QBrush(QColor(0, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.label_15.setPalette(palette1)
        self.label_15.setAutoFillBackground(True)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, -20, 91, 101))
        palette2 = QPalette()
        brush3 = QBrush(QColor(255, 255, 127, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        brush4 = QBrush(QColor(120, 120, 120, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.label_10.setPalette(palette2)
        font = QFont()
        font.setFamily(u"Century Gothic")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(-110, 0, 521, 41))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush)
        brush5 = QBrush(QColor(255, 255, 191, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush5)
        brush6 = QBrush(QColor(127, 127, 63, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush6)
        brush7 = QBrush(QColor(170, 170, 84, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush7)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush5)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush9 = QBrush(QColor(0, 0, 0, 128))
        brush9.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush10 = QBrush(QColor(0, 0, 0, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush7)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
#endif
        self.label_9.setPalette(palette3)
        font1 = QFont()
        font1.setFamily(u"Century Gothic")
        font1.setPointSize(11)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_9.setFont(font1)
        self.label_9.setToolTipDuration(-4)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(70, 30, 171, 20))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.label_11.setPalette(palette4)
        font2 = QFont()
        font2.setPointSize(7)
        self.label_11.setFont(font2)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(400, 10, 521, 41))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush5)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush6)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush7)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush5)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush12 = QBrush(QColor(0, 0, 0, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush5)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush5)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush13 = QBrush(QColor(0, 0, 0, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush13)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush14 = QBrush(QColor(0, 0, 0, 128))
        brush14.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        self.label_2.setPalette(palette5)
        font3 = QFont()
        font3.setFamily(u"Century Gothic")
        font3.setPointSize(14)
        font3.setBold(False)
        font3.setWeight(50)
        self.label_2.setFont(font3)
        self.label_2.setToolTipDuration(-4)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(820, 20, 21, 16))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(820, 10, 21, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(820, 30, 21, 16))
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 60, 891, 491))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Base, brush)
        brush15 = QBrush(QColor(159, 103, 18, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush15)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush15)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush15)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush15)
        self.label_7.setPalette(palette6)
        self.label_7.setAutoFillBackground(True)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 70, 451, 181))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush)
        brush16 = QBrush(QColor(127, 127, 127, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Dark, brush16)
        brush17 = QBrush(QColor(170, 170, 170, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette7.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush)
        palette7.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette7.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush18 = QBrush(QColor(0, 0, 0, 128))
        brush18.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush18)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette7.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush19 = QBrush(QColor(0, 0, 0, 128))
        brush19.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush19)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette7.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette7.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush20 = QBrush(QColor(0, 0, 0, 128))
        brush20.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush20)
#endif
        self.groupBox.setPalette(palette7)
        font4 = QFont()
        font4.setFamily(u"Century Gothic")
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.groupBox.setFont(font4)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 37, 61, 19))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        self.label_3.setPalette(palette8)
        font5 = QFont()
        font5.setFamily(u"Century Gothic")
        font5.setPointSize(10)
        font5.setBold(True)
        font5.setItalic(False)
        font5.setWeight(75)
        self.label_3.setFont(font5)
        self.txtIname = QLineEdit(self.groupBox)
        self.txtIname.setObjectName(u"txtIname")
        self.txtIname.setGeometry(QRect(90, 40, 341, 21))
        font6 = QFont()
        font6.setPointSize(10)
        self.txtIname.setFont(font6)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 67, 81, 19))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        self.label_4.setPalette(palette9)
        self.label_4.setFont(font5)
        self.txtIadd = QLineEdit(self.groupBox)
        self.txtIadd.setObjectName(u"txtIadd")
        self.txtIadd.setGeometry(QRect(90, 70, 341, 20))
        self.txtIadd.setFont(font6)
        self.txtIcp = QLineEdit(self.groupBox)
        self.txtIcp.setObjectName(u"txtIcp")
        self.txtIcp.setGeometry(QRect(130, 100, 301, 20))
        self.txtIcp.setFont(font6)
        self.btnSave = QPushButton(self.groupBox)
        self.btnSave.setObjectName(u"btnSave")
        self.btnSave.setGeometry(QRect(200, 130, 71, 31))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Light, brush)
        palette10.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette10.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette10.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette10.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush)
        palette10.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette10.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush21 = QBrush(QColor(0, 0, 0, 128))
        brush21.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Active, QPalette.PlaceholderText, brush21)
#endif
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette10.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush22 = QBrush(QColor(0, 0, 0, 128))
        brush22.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush22)
#endif
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette10.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette10.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush23 = QBrush(QColor(0, 0, 0, 128))
        brush23.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush23)
#endif
        self.btnSave.setPalette(palette10)
        self.btnSave.setFont(font4)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 100, 111, 19))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        self.label_5.setPalette(palette11)
        self.label_5.setFont(font5)
        self.tblCustomer = QTableWidget(self.centralwidget)
        self.tblCustomer.setObjectName(u"tblCustomer")
        self.tblCustomer.setGeometry(QRect(20, 260, 451, 261))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Base, brush)
        brush24 = QBrush(QColor(183, 72, 3, 255))
        brush24.setStyle(Qt.SolidPattern)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush24)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush24)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush24)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush24)
        self.tblCustomer.setPalette(palette12)
        font7 = QFont()
        font7.setFamily(u"Segoe UI Black")
        font7.setPointSize(9)
        font7.setBold(True)
        font7.setWeight(75)
        self.tblCustomer.setFont(font7)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(480, 70, 361, 181))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush)
        palette13.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette13.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush25 = QBrush(QColor(255, 255, 255, 128))
        brush25.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Active, QPalette.PlaceholderText, brush25)
#endif
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Midlight, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush26 = QBrush(QColor(255, 255, 255, 128))
        brush26.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush26)
#endif
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush27 = QBrush(QColor(255, 255, 255, 128))
        brush27.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush27)
#endif
        self.groupBox_2.setPalette(palette13)
        self.groupBox_2.setFont(font4)
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(140, 40, 101, 19))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.label_6.setPalette(palette14)
        self.label_6.setFont(font4)
        self.txtSearch = QLineEdit(self.groupBox_2)
        self.txtSearch.setObjectName(u"txtSearch")
        self.txtSearch.setGeometry(QRect(40, 70, 301, 20))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Button, brush)
        palette15.setBrush(QPalette.Active, QPalette.Light, brush)
        palette15.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette15.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette15.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette15.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush)
        palette15.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette15.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush28 = QBrush(QColor(0, 0, 0, 128))
        brush28.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Active, QPalette.PlaceholderText, brush28)
#endif
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette15.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette15.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush29 = QBrush(QColor(0, 0, 0, 128))
        brush29.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush29)
#endif
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette15.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette15.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette15.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush30 = QBrush(QColor(0, 0, 0, 128))
        brush30.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush30)
#endif
        self.txtSearch.setPalette(palette15)
        self.txtSearch.setFont(font6)
        self.btnSearch = QPushButton(self.groupBox_2)
        self.btnSearch.setObjectName(u"btnSearch")
        self.btnSearch.setGeometry(QRect(90, 110, 91, 31))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Button, brush)
        palette16.setBrush(QPalette.Active, QPalette.Light, brush)
        palette16.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette16.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette16.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette16.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette16.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette16.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush)
        palette16.setBrush(QPalette.Active, QPalette.Window, brush)
        palette16.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette16.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette16.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette16.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush31 = QBrush(QColor(0, 0, 0, 128))
        brush31.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Active, QPalette.PlaceholderText, brush31)
#endif
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette16.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette16.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette16.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush32 = QBrush(QColor(0, 0, 0, 128))
        brush32.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush32)
#endif
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette16.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette16.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette16.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette16.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush33 = QBrush(QColor(0, 0, 0, 128))
        brush33.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush33)
#endif
        self.btnSearch.setPalette(palette16)
        font8 = QFont()
        font8.setPointSize(10)
        font8.setBold(True)
        font8.setWeight(75)
        self.btnSearch.setFont(font8)
        self.btnView = QPushButton(self.groupBox_2)
        self.btnView.setObjectName(u"btnView")
        self.btnView.setGeometry(QRect(210, 110, 91, 31))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette17.setBrush(QPalette.Active, QPalette.Button, brush)
        palette17.setBrush(QPalette.Active, QPalette.Light, brush)
        palette17.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette17.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette17.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette17.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette17.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette17.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush)
        palette17.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette17.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette17.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette17.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush34 = QBrush(QColor(0, 0, 0, 128))
        brush34.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Active, QPalette.PlaceholderText, brush34)
#endif
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette17.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette17.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette17.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush35 = QBrush(QColor(0, 0, 0, 128))
        brush35.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush35)
#endif
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette17.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette17.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette17.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette17.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush36 = QBrush(QColor(0, 0, 0, 128))
        brush36.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush36)
#endif
        self.btnView.setPalette(palette17)
        self.btnView.setFont(font8)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(480, 260, 361, 231))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Text, brush)
        palette18.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette18.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette18.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette18.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette18.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush37 = QBrush(QColor(255, 255, 255, 128))
        brush37.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette18.setBrush(QPalette.Active, QPalette.PlaceholderText, brush37)
#endif
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Midlight, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette18.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush38 = QBrush(QColor(255, 255, 255, 128))
        brush38.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette18.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush38)
#endif
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette18.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush39 = QBrush(QColor(255, 255, 255, 128))
        brush39.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette18.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush39)
#endif
        self.groupBox_3.setPalette(palette18)
        self.groupBox_3.setFont(font4)
        self.label_12 = QLabel(self.groupBox_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(11, 70, 71, 19))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.label_12.setPalette(palette19)
        self.label_12.setFont(font4)
        self.txtNameP = QLineEdit(self.groupBox_3)
        self.txtNameP.setObjectName(u"txtNameP")
        self.txtNameP.setEnabled(True)
        self.txtNameP.setGeometry(QRect(60, 70, 281, 20))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette20.setBrush(QPalette.Active, QPalette.Button, brush)
        palette20.setBrush(QPalette.Active, QPalette.Light, brush)
        palette20.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette20.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette20.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette20.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette20.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette20.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette20.setBrush(QPalette.Active, QPalette.Base, brush)
        palette20.setBrush(QPalette.Active, QPalette.Window, brush)
        palette20.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette20.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette20.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette20.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush40 = QBrush(QColor(0, 0, 0, 128))
        brush40.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette20.setBrush(QPalette.Active, QPalette.PlaceholderText, brush40)
#endif
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette20.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette20.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette20.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette20.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette20.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette20.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette20.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush41 = QBrush(QColor(0, 0, 0, 128))
        brush41.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette20.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush41)
#endif
        palette20.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette20.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette20.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette20.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette20.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette20.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette20.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette20.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush42 = QBrush(QColor(0, 0, 0, 128))
        brush42.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette20.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush42)
#endif
        self.txtNameP.setPalette(palette20)
        self.txtNameP.setFont(font6)
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(11, 100, 71, 19))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.label_13.setPalette(palette21)
        self.label_13.setFont(font4)
        self.txtAddressP = QLineEdit(self.groupBox_3)
        self.txtAddressP.setObjectName(u"txtAddressP")
        self.txtAddressP.setEnabled(True)
        self.txtAddressP.setGeometry(QRect(80, 100, 261, 20))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette22.setBrush(QPalette.Active, QPalette.Button, brush)
        palette22.setBrush(QPalette.Active, QPalette.Light, brush)
        palette22.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette22.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette22.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette22.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette22.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette22.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette22.setBrush(QPalette.Active, QPalette.Base, brush)
        palette22.setBrush(QPalette.Active, QPalette.Window, brush)
        palette22.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette22.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette22.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette22.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush43 = QBrush(QColor(0, 0, 0, 128))
        brush43.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette22.setBrush(QPalette.Active, QPalette.PlaceholderText, brush43)
#endif
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette22.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette22.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette22.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette22.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette22.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette22.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette22.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush44 = QBrush(QColor(0, 0, 0, 128))
        brush44.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette22.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush44)
#endif
        palette22.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette22.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette22.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette22.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette22.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette22.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette22.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette22.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush45 = QBrush(QColor(0, 0, 0, 128))
        brush45.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette22.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush45)
#endif
        self.txtAddressP.setPalette(palette22)
        self.txtAddressP.setFont(font6)
        self.txtContactP = QLineEdit(self.groupBox_3)
        self.txtContactP.setObjectName(u"txtContactP")
        self.txtContactP.setEnabled(True)
        self.txtContactP.setGeometry(QRect(140, 130, 201, 20))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette23.setBrush(QPalette.Active, QPalette.Button, brush)
        palette23.setBrush(QPalette.Active, QPalette.Light, brush)
        palette23.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette23.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette23.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette23.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette23.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette23.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette23.setBrush(QPalette.Active, QPalette.Base, brush)
        palette23.setBrush(QPalette.Active, QPalette.Window, brush)
        palette23.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette23.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette23.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette23.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush46 = QBrush(QColor(0, 0, 0, 128))
        brush46.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette23.setBrush(QPalette.Active, QPalette.PlaceholderText, brush46)
#endif
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette23.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette23.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette23.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette23.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette23.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette23.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette23.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush47 = QBrush(QColor(0, 0, 0, 128))
        brush47.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette23.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush47)
#endif
        palette23.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette23.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette23.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette23.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette23.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette23.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette23.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette23.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush48 = QBrush(QColor(0, 0, 0, 128))
        brush48.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette23.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush48)
#endif
        self.txtContactP.setPalette(palette23)
        self.txtContactP.setFont(font6)
        self.label_14 = QLabel(self.groupBox_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 130, 131, 19))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.label_14.setPalette(palette24)
        self.label_14.setFont(font4)
        self.label_16 = QLabel(self.groupBox_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(11, 40, 151, 20))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.label_16.setPalette(palette25)
        self.label_16.setFont(font4)
        self.txtNo = QLineEdit(self.groupBox_3)
        self.txtNo.setObjectName(u"txtNo")
        self.txtNo.setEnabled(False)
        self.txtNo.setGeometry(QRect(150, 40, 191, 20))
        palette26 = QPalette()
        palette26.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette26.setBrush(QPalette.Active, QPalette.Button, brush)
        palette26.setBrush(QPalette.Active, QPalette.Light, brush)
        palette26.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette26.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette26.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette26.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette26.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette26.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette26.setBrush(QPalette.Active, QPalette.Base, brush)
        palette26.setBrush(QPalette.Active, QPalette.Window, brush)
        palette26.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette26.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette26.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette26.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush49 = QBrush(QColor(0, 0, 0, 128))
        brush49.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette26.setBrush(QPalette.Active, QPalette.PlaceholderText, brush49)
#endif
        palette26.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette26.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette26.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette26.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette26.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette26.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette26.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette26.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush50 = QBrush(QColor(0, 0, 0, 128))
        brush50.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette26.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush50)
#endif
        palette26.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette26.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette26.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette26.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette26.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette26.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette26.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette26.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette26.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette26.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette26.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette26.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette26.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette26.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette26.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush51 = QBrush(QColor(0, 0, 0, 128))
        brush51.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette26.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush51)
#endif
        self.txtNo.setPalette(palette26)
        self.txtNo.setFont(font6)
        self.btnUpdate = QPushButton(self.groupBox_3)
        self.btnUpdate.setObjectName(u"btnUpdate")
        self.btnUpdate.setGeometry(QRect(100, 180, 181, 31))
        palette27 = QPalette()
        palette27.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette27.setBrush(QPalette.Active, QPalette.Button, brush)
        palette27.setBrush(QPalette.Active, QPalette.Light, brush)
        palette27.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette27.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette27.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette27.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette27.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette27.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette27.setBrush(QPalette.Active, QPalette.Base, brush)
        palette27.setBrush(QPalette.Active, QPalette.Window, brush)
        palette27.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette27.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette27.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette27.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush52 = QBrush(QColor(0, 0, 0, 128))
        brush52.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette27.setBrush(QPalette.Active, QPalette.PlaceholderText, brush52)
#endif
        palette27.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette27.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette27.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette27.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette27.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette27.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette27.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette27.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette27.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette27.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette27.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette27.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette27.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette27.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette27.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush53 = QBrush(QColor(0, 0, 0, 128))
        brush53.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette27.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush53)
#endif
        palette27.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette27.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette27.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette27.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette27.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette27.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette27.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette27.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette27.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette27.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette27.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette27.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette27.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette27.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette27.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush54 = QBrush(QColor(0, 0, 0, 128))
        brush54.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette27.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush54)
#endif
        self.btnUpdate.setPalette(palette27)
        self.btnUpdate.setFont(font4)
        self.btnDelete = QPushButton(self.centralwidget)
        self.btnDelete.setObjectName(u"btnDelete")
        self.btnDelete.setGeometry(QRect(720, 500, 71, 31))
        palette28 = QPalette()
        palette28.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette28.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette28.setBrush(QPalette.Active, QPalette.Light, brush)
        palette28.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette28.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette28.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette28.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette28.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette28.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette28.setBrush(QPalette.Active, QPalette.Base, brush)
        palette28.setBrush(QPalette.Active, QPalette.Window, brush)
        palette28.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette28.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette28.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette28.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush55 = QBrush(QColor(0, 0, 0, 128))
        brush55.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette28.setBrush(QPalette.Active, QPalette.PlaceholderText, brush55)
#endif
        palette28.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette28.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette28.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette28.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette28.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette28.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette28.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette28.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette28.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette28.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette28.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette28.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette28.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette28.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette28.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush56 = QBrush(QColor(0, 0, 0, 128))
        brush56.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette28.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush56)
#endif
        palette28.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette28.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette28.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette28.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette28.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette28.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette28.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette28.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette28.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette28.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette28.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette28.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette28.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette28.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette28.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush57 = QBrush(QColor(0, 0, 0, 128))
        brush57.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette28.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush57)
#endif
        self.btnDelete.setPalette(palette28)
        self.btnDelete.setFont(font4)
        self.btnProfile = QPushButton(self.centralwidget)
        self.btnProfile.setObjectName(u"btnProfile")
        self.btnProfile.setGeometry(QRect(580, 500, 131, 31))
        palette29 = QPalette()
        palette29.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette29.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette29.setBrush(QPalette.Active, QPalette.Light, brush)
        palette29.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette29.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette29.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette29.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette29.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette29.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette29.setBrush(QPalette.Active, QPalette.Base, brush)
        palette29.setBrush(QPalette.Active, QPalette.Window, brush)
        palette29.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette29.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette29.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette29.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush58 = QBrush(QColor(0, 0, 0, 128))
        brush58.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette29.setBrush(QPalette.Active, QPalette.PlaceholderText, brush58)
#endif
        palette29.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette29.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette29.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette29.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette29.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette29.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette29.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette29.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette29.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette29.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette29.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette29.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette29.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette29.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette29.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush59 = QBrush(QColor(0, 0, 0, 128))
        brush59.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette29.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush59)
#endif
        palette29.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette29.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette29.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette29.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette29.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette29.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette29.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette29.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette29.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette29.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette29.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette29.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette29.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette29.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette29.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush60 = QBrush(QColor(0, 0, 0, 128))
        brush60.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette29.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush60)
#endif
        self.btnProfile.setPalette(palette29)
        self.btnProfile.setFont(font4)
        RoomInventory.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(RoomInventory)
        self.statusbar.setObjectName(u"statusbar")
        RoomInventory.setStatusBar(self.statusbar)

        self.retranslateUi(RoomInventory)

        QMetaObject.connectSlotsByName(RoomInventory)
    # setupUi

    def retranslateUi(self, RoomInventory):
        RoomInventory.setWindowTitle(QCoreApplication.translate("RoomInventory", u"INVENTORY", None))
        self.label_15.setText("")
        self.label_10.setText(QCoreApplication.translate("RoomInventory", u"O", None))
        self.label_9.setText(QCoreApplication.translate("RoomInventory", u"H O T E L   D E L   L U N A ", None))
        self.label_11.setText(QCoreApplication.translate("RoomInventory", u"A   P L A C E   L I K E    H O M E", None))
        self.label_2.setText(QCoreApplication.translate("RoomInventory", u"R o o m   I n v e n t o r y", None))
        self.label_7.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("RoomInventory", u"CUSTOMER INFORMATION", None))
        self.label_3.setText(QCoreApplication.translate("RoomInventory", u"NAME :", None))
        self.label_4.setText(QCoreApplication.translate("RoomInventory", u"ADDRESS :", None))
        self.btnSave.setText(QCoreApplication.translate("RoomInventory", u"Save", None))
        self.label_5.setText(QCoreApplication.translate("RoomInventory", u"CONTACT NO. :", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("RoomInventory", u"SEARCH CUSTOMER", None))
        self.label_6.setText(QCoreApplication.translate("RoomInventory", u"Enter Name :", None))
        self.btnSearch.setText(QCoreApplication.translate("RoomInventory", u"Search", None))
        self.btnView.setText(QCoreApplication.translate("RoomInventory", u"View All", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("RoomInventory", u"CUSTOMER PROFILE", None))
        self.label_12.setText(QCoreApplication.translate("RoomInventory", u"Name :", None))
        self.label_13.setText(QCoreApplication.translate("RoomInventory", u"Address :", None))
        self.label_14.setText(QCoreApplication.translate("RoomInventory", u"Contact Number :", None))
        self.label_16.setText(QCoreApplication.translate("RoomInventory", u"Customer Number :", None))
        self.btnUpdate.setText(QCoreApplication.translate("RoomInventory", u"Update Information", None))
        self.btnDelete.setText(QCoreApplication.translate("RoomInventory", u"Delete", None))
        self.btnProfile.setText(QCoreApplication.translate("RoomInventory", u"View Profile", None))
    # retranslateUi

