# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MAINAdDphk.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *

import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1010, 582)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(157, 102, 18, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 0, 1001, 571))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Base, brush)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.label_14.setPalette(palette1)
        font = QFont()
        font.setPointSize(7)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(True)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 0, 1011, 61))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Base, brush)
        brush2 = QBrush(QColor(0, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.label_15.setPalette(palette2)
        self.label_15.setAutoFillBackground(True)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(110, 200, 431, 151))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush)
        brush3 = QBrush(QColor(173, 59, 7, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        brush4 = QBrush(QColor(120, 120, 120, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.label_7.setPalette(palette3)
        font1 = QFont()
        font1.setFamily(u"Century Gothic")
        font1.setPointSize(72)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_7.setFont(font1)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(140, 300, 371, 151))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.label_16.setPalette(palette4)
        self.label_16.setFont(font1)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(220, 300, 141, 51))
        palette5 = QPalette()
        brush5 = QBrush(QColor(255, 255, 127, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.label_13.setPalette(palette5)
        font2 = QFont()
        font2.setFamily(u"Palace Script MT")
        font2.setPointSize(72)
        font2.setItalic(True)
        self.label_13.setFont(font2)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(210, 430, 291, 20))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.label_17.setPalette(palette6)
        font3 = QFont()
        font3.setFamily(u"Century Gothic")
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setWeight(75)
        self.label_17.setFont(font3)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(590, 10, 431, 41))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush5)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush)
        brush6 = QBrush(QColor(255, 255, 191, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush6)
        brush7 = QBrush(QColor(127, 127, 63, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Dark, brush7)
        brush8 = QBrush(QColor(170, 170, 84, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Mid, brush8)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette7.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette7.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette7.setBrush(QPalette.Active, QPalette.AlternateBase, brush6)
        brush9 = QBrush(QColor(255, 255, 220, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush10 = QBrush(QColor(0, 0, 0, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.Mid, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush11)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.Dark, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.Mid, brush8)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush12 = QBrush(QColor(0, 0, 0, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.label_2.setPalette(palette7)
        font4 = QFont()
        font4.setFamily(u"Century Gothic")
        font4.setPointSize(12)
        font4.setBold(False)
        font4.setItalic(False)
        font4.setWeight(50)
        self.label_2.setFont(font4)
        self.label_2.setToolTipDuration(-4)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 80, 591, 71))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush5)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush)
        palette8.setBrush(QPalette.Active, QPalette.Midlight, brush6)
        palette8.setBrush(QPalette.Active, QPalette.Dark, brush7)
        palette8.setBrush(QPalette.Active, QPalette.Mid, brush8)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette8.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette8.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette8.setBrush(QPalette.Active, QPalette.AlternateBase, brush6)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush13 = QBrush(QColor(0, 0, 0, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush13)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush5)
        palette8.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.Mid, brush8)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette8.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush14 = QBrush(QColor(0, 0, 0, 128))
        brush14.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush14)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Midlight, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Dark, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.Mid, brush8)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush15 = QBrush(QColor(0, 0, 0, 128))
        brush15.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush15)
#endif
        self.label.setPalette(palette8)
        font5 = QFont()
        font5.setFamily(u"Century Gothic")
        font5.setPointSize(26)
        font5.setBold(True)
        font5.setItalic(False)
        font5.setWeight(75)
        self.label.setFont(font5)
        self.label.setToolTipDuration(-4)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(Qt.AlignCenter)
        self.btnBooking = QPushButton(self.centralwidget)
        self.btnBooking.setObjectName(u"btnBooking")
        self.btnBooking.setGeometry(QRect(600, 110, 381, 81))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        brush16 = QBrush(QColor(15, 1, 1, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush16)
        palette9.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Dark, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Mid, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette9.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Highlight, brush1)
        palette9.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette9.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipBase, brush1)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush17 = QBrush(QColor(157, 102, 18, 128))
        brush17.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Active, QPalette.PlaceholderText, brush17)
#endif
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush16)
        palette9.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Dark, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Mid, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush18 = QBrush(QColor(157, 102, 18, 128))
        brush18.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush18)
#endif
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush16)
        palette9.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Dark, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Mid, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        brush19 = QBrush(QColor(0, 120, 215, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Disabled, QPalette.Highlight, brush19)
        palette9.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush20 = QBrush(QColor(157, 102, 18, 128))
        brush20.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush20)
#endif
        self.btnBooking.setPalette(palette9)
        font6 = QFont()
        font6.setFamily(u"Century Gothic")
        font6.setPointSize(18)
        font6.setBold(True)
        font6.setWeight(75)
        self.btnBooking.setFont(font6)
        self.btnBooking.setAutoFillBackground(True)
        self.btnBooking.setAutoDefault(True)
        self.btnBooking.setFlat(True)
        self.btnRoom = QPushButton(self.centralwidget)
        self.btnRoom.setObjectName(u"btnRoom")
        self.btnRoom.setGeometry(QRect(600, 270, 381, 91))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush16)
        palette10.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Dark, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Mid, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette10.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Highlight, brush1)
        palette10.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette10.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipBase, brush1)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush21 = QBrush(QColor(157, 102, 18, 128))
        brush21.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Active, QPalette.PlaceholderText, brush21)
#endif
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush16)
        palette10.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Dark, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Mid, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush22 = QBrush(QColor(157, 102, 18, 128))
        brush22.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush22)
#endif
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush16)
        palette10.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Dark, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Mid, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Highlight, brush19)
        palette10.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush23 = QBrush(QColor(157, 102, 18, 128))
        brush23.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush23)
#endif
        self.btnRoom.setPalette(palette10)
        self.btnRoom.setFont(font6)
        self.btnRoom.setAutoFillBackground(True)
        self.btnRoom.setAutoDefault(True)
        self.btnRoom.setFlat(True)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(50, 180, 491, 321))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Base, brush)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.label_6.setPalette(palette11)
        font7 = QFont()
        font7.setUnderline(False)
        self.label_6.setFont(font7)
        self.label_6.setAutoFillBackground(True)
        self.label_6.setFrameShadow(QFrame.Plain)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 200, 541, 281))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Base, brush)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.label_8.setPalette(palette12)
        self.label_8.setFont(font7)
        self.label_8.setAutoFillBackground(True)
        self.label_8.setFrameShadow(QFrame.Plain)
        self.btnExit = QPushButton(self.centralwidget)
        self.btnExit.setObjectName(u"btnExit")
        self.btnExit.setGeometry(QRect(600, 440, 381, 81))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush16)
        palette13.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Dark, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Mid, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette13.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Highlight, brush1)
        palette13.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette13.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipBase, brush1)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        brush24 = QBrush(QColor(157, 102, 18, 128))
        brush24.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Active, QPalette.PlaceholderText, brush24)
#endif
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush16)
        palette13.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Dark, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Mid, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        brush25 = QBrush(QColor(157, 102, 18, 128))
        brush25.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush25)
#endif
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush16)
        palette13.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Dark, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Mid, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Highlight, brush19)
        palette13.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush26 = QBrush(QColor(157, 102, 18, 128))
        brush26.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush26)
#endif
        self.btnExit.setPalette(palette13)
        self.btnExit.setFont(font6)
        self.btnExit.setAutoFillBackground(True)
        self.btnExit.setAutoDefault(True)
        self.btnExit.setFlat(True)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(650, 220, 291, 16))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush)
        palette14.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette14.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush27 = QBrush(QColor(255, 255, 255, 128))
        brush27.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Active, QPalette.PlaceholderText, brush27)
#endif
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Midlight, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush28 = QBrush(QColor(255, 255, 255, 128))
        brush28.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush28)
#endif
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette14.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush29 = QBrush(QColor(255, 255, 255, 128))
        brush29.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush29)
#endif
        self.line.setPalette(palette14)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(660, 400, 291, 16))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush)
        palette15.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette15.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush30 = QBrush(QColor(255, 255, 255, 128))
        brush30.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Active, QPalette.PlaceholderText, brush30)
#endif
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Midlight, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush31 = QBrush(QColor(255, 255, 255, 128))
        brush31.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush31)
#endif
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette15.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush32 = QBrush(QColor(255, 255, 255, 128))
        brush32.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush32)
#endif
        self.line_2.setPalette(palette15)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(980, 30, 21, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(980, 20, 21, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(980, 10, 21, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 120, 591, 71))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette16.setBrush(QPalette.Active, QPalette.Button, brush5)
        palette16.setBrush(QPalette.Active, QPalette.Light, brush)
        palette16.setBrush(QPalette.Active, QPalette.Midlight, brush6)
        palette16.setBrush(QPalette.Active, QPalette.Dark, brush7)
        palette16.setBrush(QPalette.Active, QPalette.Mid, brush8)
        palette16.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette16.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette16.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush)
        palette16.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette16.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette16.setBrush(QPalette.Active, QPalette.AlternateBase, brush6)
        palette16.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette16.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush33 = QBrush(QColor(0, 0, 0, 128))
        brush33.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Active, QPalette.PlaceholderText, brush33)
#endif
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush5)
        palette16.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette16.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette16.setBrush(QPalette.Inactive, QPalette.Mid, brush8)
        palette16.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette16.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush6)
        palette16.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette16.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush34 = QBrush(QColor(0, 0, 0, 128))
        brush34.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush34)
#endif
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush5)
        palette16.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.Midlight, brush6)
        palette16.setBrush(QPalette.Disabled, QPalette.Dark, brush7)
        palette16.setBrush(QPalette.Disabled, QPalette.Mid, brush8)
        palette16.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette16.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette16.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush5)
        palette16.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette16.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush35 = QBrush(QColor(0, 0, 0, 128))
        brush35.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush35)
#endif
        self.label_3.setPalette(palette16)
        font8 = QFont()
        font8.setFamily(u"Century Gothic")
        font8.setPointSize(14)
        font8.setBold(False)
        font8.setItalic(False)
        font8.setWeight(50)
        self.label_3.setFont(font8)
        self.label_3.setToolTipDuration(-4)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(-120, 0, 521, 41))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette17.setBrush(QPalette.Active, QPalette.Button, brush5)
        palette17.setBrush(QPalette.Active, QPalette.Light, brush)
        palette17.setBrush(QPalette.Active, QPalette.Midlight, brush6)
        palette17.setBrush(QPalette.Active, QPalette.Dark, brush7)
        palette17.setBrush(QPalette.Active, QPalette.Mid, brush8)
        palette17.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette17.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette17.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette17.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette17.setBrush(QPalette.Active, QPalette.AlternateBase, brush6)
        palette17.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette17.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush36 = QBrush(QColor(0, 0, 0, 128))
        brush36.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Active, QPalette.PlaceholderText, brush36)
#endif
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush5)
        palette17.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette17.setBrush(QPalette.Inactive, QPalette.Dark, brush7)
        palette17.setBrush(QPalette.Inactive, QPalette.Mid, brush8)
        palette17.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette17.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush6)
        palette17.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette17.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
        brush37 = QBrush(QColor(0, 0, 0, 128))
        brush37.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush37)
#endif
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush5)
        palette17.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Midlight, brush6)
        palette17.setBrush(QPalette.Disabled, QPalette.Dark, brush7)
        palette17.setBrush(QPalette.Disabled, QPalette.Mid, brush8)
        palette17.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette17.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette17.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush5)
        palette17.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette17.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush38 = QBrush(QColor(0, 0, 0, 128))
        brush38.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush38)
#endif
        self.label_9.setPalette(palette17)
        font9 = QFont()
        font9.setFamily(u"Century Gothic")
        font9.setPointSize(10)
        font9.setBold(True)
        font9.setWeight(75)
        self.label_9.setFont(font9)
        self.label_9.setToolTipDuration(-4)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, -30, 91, 101))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.label_10.setPalette(palette18)
        font10 = QFont()
        font10.setFamily(u"Century Gothic")
        font10.setPointSize(22)
        font10.setBold(False)
        font10.setWeight(50)
        self.label_10.setFont(font10)
        self.label_10.setAutoFillBackground(False)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(60, 30, 171, 20))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.label_11.setPalette(palette19)
        self.label_11.setFont(font)
        self.QuestionButton = QPushButton(self.centralwidget)
        self.QuestionButton.setObjectName(u"QuestionButton")
        self.QuestionButton.setGeometry(QRect(50, 510, 37, 33))
        icon = QIcon()
        icon.addFile("url(:/images/images/question-mark-inside-a-circle.png)")
        self.QuestionButton.setIcon(icon)
        self.QuestionButton.setIconSize(QSize(25, 25))
        self.QuestionButton.setFlat(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_14.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_15.raise_()
        self.label_7.raise_()
        self.label_16.raise_()
        self.label_13.raise_()
        self.label_17.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.btnBooking.raise_()
        self.btnRoom.raise_()
        self.btnExit.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.label_3.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.QuestionButton.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.btnBooking.setDefault(False)
        self.btnRoom.setDefault(False)
        self.btnExit.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"HOTEL DEL LUNA ONLINE RESERVATION", None))
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"H O T E L", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"L U N A", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"    del", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"A   P L A C E   L I K E    H O M E", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"O n l i n e   H o t e l   R e s e r v a t i o n", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"W   E   L   C   O   M   E", None))
        self.btnBooking.setText(QCoreApplication.translate("MainWindow", u"H O T E L   B O O K I N G", None))
        self.btnRoom.setText(QCoreApplication.translate("MainWindow", u"R O O M   I N F O R M A T I O N", None))
        self.label_6.setText("")
        self.label_8.setText("")
        self.btnExit.setText(QCoreApplication.translate("MainWindow", u"E X I T", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"T O", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"H O T E L   D E L   L U N A ", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"O", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"A   P L A C E   L I K E    H O M E", None))
        self.QuestionButton.setText("")
    # retranslateUi

