# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'recordYIomDB.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_ReservationRecord(object):
    def setupUi(self, ReservationRecord):
        if ReservationRecord.objectName():
            ReservationRecord.setObjectName(u"ReservationRecord")
        ReservationRecord.resize(733, 570)
        self.buttonBox = QDialogButtonBox(ReservationRecord)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(70, 510, 341, 32))
        palette = QPalette()
        brush = QBrush(QColor(159, 103, 18, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush1 = QBrush(QColor(120, 120, 120, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        self.buttonBox.setPalette(palette)
        font = QFont()
        font.setFamily(u"Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Close)
        self.label_4 = QLabel(ReservationRecord)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(70, 370, 611, 121))
        palette1 = QPalette()
        brush2 = QBrush(QColor(255, 255, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush2)
        brush3 = QBrush(QColor(255, 255, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush3)
        brush4 = QBrush(QColor(255, 255, 191, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush4)
        brush5 = QBrush(QColor(127, 127, 63, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush5)
        brush6 = QBrush(QColor(170, 170, 84, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush6)
        brush7 = QBrush(QColor(0, 0, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush3)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
        brush9 = QBrush(QColor(0, 0, 0, 128))
        brush9.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
        brush10 = QBrush(QColor(0, 0, 0, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
#endif
        self.label_4.setPalette(palette1)
        font1 = QFont()
        font1.setFamily(u"Century Gothic")
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setWeight(50)
        self.label_4.setFont(font1)
        self.label_4.setToolTipDuration(-4)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_2 = QLabel(ReservationRecord)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 30, 521, 41))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush5)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush3)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
        brush12 = QBrush(QColor(0, 0, 0, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
        brush13 = QBrush(QColor(0, 0, 0, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush13)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
        brush14 = QBrush(QColor(0, 0, 0, 128))
        brush14.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        self.label_2.setPalette(palette2)
        font2 = QFont()
        font2.setFamily(u"Century Gothic")
        font2.setPointSize(12)
        font2.setBold(False)
        font2.setWeight(50)
        self.label_2.setFont(font2)
        self.label_2.setToolTipDuration(-4)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.listView = QListView(ReservationRecord)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(60, 90, 611, 261))
        self.label_3 = QLabel(ReservationRecord)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 120, 91, 16))
        self.label_3.setWordWrap(True)
        self.label_5 = QLabel(ReservationRecord)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(300, 120, 161, 16))
        self.label_5.setWordWrap(True)
        self.label_6 = QLabel(ReservationRecord)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(530, 120, 161, 16))
        self.label_6.setWordWrap(True)
        self.label_7 = QLabel(ReservationRecord)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 0, 731, 571))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.label_7.setPalette(palette3)
        self.label_7.setAutoFillBackground(True)
        self.label_8 = QLabel(ReservationRecord)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 20, 691, 531))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush7)
        self.label_8.setPalette(palette4)
        self.label_8.setAutoFillBackground(True)
        self.label = QLabel(ReservationRecord)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 0, 691, 41))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush5)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush6)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush3)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
        brush15 = QBrush(QColor(0, 0, 0, 128))
        brush15.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush15)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush5)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
        brush16 = QBrush(QColor(0, 0, 0, 128))
        brush16.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush16)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
        brush17 = QBrush(QColor(0, 0, 0, 128))
        brush17.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush17)
#endif
        self.label.setPalette(palette5)
        font3 = QFont()
        font3.setFamily(u"Century Gothic")
        font3.setPointSize(24)
        font3.setBold(True)
        font3.setWeight(75)
        self.label.setFont(font3)
        self.label.setToolTipDuration(-4)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(ReservationRecord)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(300, 60, 171, 20))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_9.setPalette(palette6)
        font4 = QFont()
        font4.setPointSize(8)
        self.label_9.setFont(font4)
        self.label_7.raise_()
        self.label_8.raise_()
        self.buttonBox.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.listView.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.label_9.raise_()

        self.retranslateUi(ReservationRecord)
        # self.buttonBox.accepted.connect(ReservationRecord.accept)
        # self.buttonBox.rejected.connect(ReservationRecord.reject)

        QMetaObject.connectSlotsByName(ReservationRecord)
    # setupUi

    def retranslateUi(self, ReservationRecord):
        ReservationRecord.setWindowTitle(QCoreApplication.translate("ReservationRecord", u"ReservationRecord", None))
        self.label_4.setText(QCoreApplication.translate("ReservationRecord", u"In accordance with the released Inter-Agency Task Force for the Management of Emerging Infectious Disease or the IATF - EID rules, upon arrival in the hotel there will be checking of temperature. Every visitors will fill-out the Health Declaration Form for contact tracing, face mask and face shield shall be worn at all times inside the hotel premises. Everyone must observe at least 2 meter social distance and ordered to follow all the given health protocols. Fail of compliance will cause consequence for the both guest/s and  hotel management. Thank you for your understanding and cooperation.", None))
        self.label_2.setText(QCoreApplication.translate("ReservationRecord", u"R e s e r v a t i o n   S u m m a r y ", None))
        self.label_3.setText(QCoreApplication.translate("ReservationRecord", u"Customer Name", None))
        self.label_5.setText(QCoreApplication.translate("ReservationRecord", u"Reservation  Time and Date", None))
        self.label_6.setText(QCoreApplication.translate("ReservationRecord", u"Reservation Status", None))
        self.label_7.setText("")
        self.label_8.setText(QCoreApplication.translate("ReservationRecord", u"TextLabel", None))
        self.label.setText(QCoreApplication.translate("ReservationRecord", u"H O T E L   D E L   L U N A", None))
        self.label_9.setText(QCoreApplication.translate("ReservationRecord", u"A   P L A C E   L I K E    H O M E", None))
    # retranslateUi

