# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ROOM-INFORMATIONcKIvqn.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_RoomInfo(object):
    def setupUi(self, RoomInfo):
        if RoomInfo.objectName():
            RoomInfo.setObjectName(u"RoomInfo")
        RoomInfo.resize(927, 619)
        self.buttonBox = QDialogButtonBox(RoomInfo)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(-160, 570, 681, 61))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Close)
        self.label_2 = QLabel(RoomInfo)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 30, 791, 41))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 127, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush)
        brush2 = QBrush(QColor(255, 255, 191, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        brush3 = QBrush(QColor(127, 127, 63, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush3)
        brush4 = QBrush(QColor(170, 170, 84, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush4)
        brush5 = QBrush(QColor(0, 0, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        brush6 = QBrush(QColor(255, 255, 220, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush7 = QBrush(QColor(0, 0, 0, 128))
        brush7.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush5)
        brush8 = QBrush(QColor(0, 0, 0, 128))
        brush8.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush5)
        brush9 = QBrush(QColor(0, 0, 0, 128))
        brush9.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.label_2.setPalette(palette)
        font = QFont()
        font.setFamily(u"Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setToolTipDuration(-4)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(RoomInfo)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(100, 90, 351, 221))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush10 = QBrush(QColor(120, 120, 120, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox.setPalette(palette1)
        font1 = QFont()
        font1.setFamily(u"Century Gothic")
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setWeight(75)
        self.groupBox.setFont(font1)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 30, 181, 20))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_3.setPalette(palette2)
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(False)
        font2.setWeight(50)
        self.label_3.setFont(font2)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 60, 231, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_11.setPalette(palette3)
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(False)
        font3.setWeight(50)
        self.label_11.setFont(font3)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 80, 231, 31))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_12.setPalette(palette4)
        self.label_12.setFont(font3)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 100, 231, 31))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_13.setPalette(palette5)
        self.label_13.setFont(font3)
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(30, 120, 231, 31))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_14.setPalette(palette6)
        self.label_14.setFont(font3)
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 140, 231, 31))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_15.setPalette(palette7)
        self.label_15.setFont(font3)
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 160, 231, 31))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_16.setPalette(palette8)
        self.label_16.setFont(font3)
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 180, 301, 31))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_17.setPalette(palette9)
        self.label_17.setFont(font3)
        self.label = QLabel(RoomInfo)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(200, 0, 521, 41))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Light, brush)
        palette10.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette10.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Shadow, brush5)
        palette10.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Midlight, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Dark, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette10.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Shadow, brush5)
        palette10.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush5)
        brush12 = QBrush(QColor(0, 0, 0, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Shadow, brush5)
        palette10.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush5)
        brush13 = QBrush(QColor(0, 0, 0, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush13)
#endif
        self.label.setPalette(palette10)
        font4 = QFont()
        font4.setFamily(u"Century Gothic")
        font4.setPointSize(26)
        font4.setBold(True)
        font4.setWeight(75)
        self.label.setFont(font4)
        self.label.setToolTipDuration(-4)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(RoomInfo)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 0, 931, 621))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Base, brush)
        brush14 = QBrush(QColor(159, 103, 18, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        self.label_5.setPalette(palette11)
        self.label_5.setAutoFillBackground(True)
        self.label_7 = QLabel(RoomInfo)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 20, 881, 581))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Base, brush)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        self.label_7.setPalette(palette12)
        self.label_7.setAutoFillBackground(True)
        self.label_10 = QLabel(RoomInfo)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(390, 60, 171, 20))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_10.setPalette(palette13)
        font5 = QFont()
        font5.setPointSize(8)
        self.label_10.setFont(font5)
        self.groupBox_4 = QGroupBox(RoomInfo)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(100, 330, 351, 241))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox_4.setPalette(palette14)
        self.groupBox_4.setFont(font1)
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 30, 181, 20))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_4.setPalette(palette15)
        self.label_4.setFont(font2)
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 60, 231, 31))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_18.setPalette(palette16)
        self.label_18.setFont(font3)
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 80, 231, 31))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_19.setPalette(palette17)
        self.label_19.setFont(font3)
        self.label_20 = QLabel(self.groupBox_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 100, 231, 31))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_20.setPalette(palette18)
        self.label_20.setFont(font3)
        self.label_21 = QLabel(self.groupBox_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 120, 231, 31))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_21.setPalette(palette19)
        self.label_21.setFont(font3)
        self.label_22 = QLabel(self.groupBox_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 140, 231, 31))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette20.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_22.setPalette(palette20)
        self.label_22.setFont(font3)
        self.label_23 = QLabel(self.groupBox_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(30, 160, 231, 31))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_23.setPalette(palette21)
        self.label_23.setFont(font3)
        self.label_24 = QLabel(self.groupBox_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(30, 180, 301, 31))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette22.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_24.setPalette(palette22)
        self.label_24.setFont(font3)
        self.label_25 = QLabel(self.groupBox_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(30, 200, 301, 31))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette23.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_25.setPalette(palette23)
        self.label_25.setFont(font3)
        self.groupBox_6 = QGroupBox(RoomInfo)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(510, 90, 351, 221))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox_6.setPalette(palette24)
        self.groupBox_6.setFont(font1)
        self.label_6 = QLabel(self.groupBox_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 30, 181, 20))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette25.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_6.setPalette(palette25)
        self.label_6.setFont(font2)
        self.label_26 = QLabel(self.groupBox_6)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(30, 60, 231, 31))
        palette26 = QPalette()
        palette26.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette26.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette26.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_26.setPalette(palette26)
        self.label_26.setFont(font3)
        self.label_27 = QLabel(self.groupBox_6)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(30, 80, 231, 31))
        palette27 = QPalette()
        palette27.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette27.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette27.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_27.setPalette(palette27)
        self.label_27.setFont(font3)
        self.label_28 = QLabel(self.groupBox_6)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(30, 100, 231, 31))
        palette28 = QPalette()
        palette28.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette28.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette28.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_28.setPalette(palette28)
        self.label_28.setFont(font3)
        self.label_29 = QLabel(self.groupBox_6)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(30, 120, 231, 31))
        palette29 = QPalette()
        palette29.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette29.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette29.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_29.setPalette(palette29)
        self.label_29.setFont(font3)
        self.label_30 = QLabel(self.groupBox_6)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(30, 140, 231, 31))
        palette30 = QPalette()
        palette30.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette30.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette30.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_30.setPalette(palette30)
        self.label_30.setFont(font3)
        self.label_31 = QLabel(self.groupBox_6)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(30, 160, 231, 31))
        palette31 = QPalette()
        palette31.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette31.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette31.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_31.setPalette(palette31)
        self.label_31.setFont(font3)
        self.label_32 = QLabel(self.groupBox_6)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(30, 180, 301, 31))
        palette32 = QPalette()
        palette32.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette32.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette32.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_32.setPalette(palette32)
        self.label_32.setFont(font3)
        self.groupBox_7 = QGroupBox(RoomInfo)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(510, 330, 351, 251))
        palette33 = QPalette()
        palette33.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette33.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette33.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.groupBox_7.setPalette(palette33)
        self.groupBox_7.setFont(font1)
        self.label_8 = QLabel(self.groupBox_7)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(100, 30, 181, 20))
        palette34 = QPalette()
        palette34.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette34.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette34.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_8.setPalette(palette34)
        self.label_8.setFont(font2)
        self.label_33 = QLabel(self.groupBox_7)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(30, 60, 231, 31))
        palette35 = QPalette()
        palette35.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette35.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette35.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_33.setPalette(palette35)
        self.label_33.setFont(font3)
        self.label_34 = QLabel(self.groupBox_7)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(30, 80, 231, 31))
        palette36 = QPalette()
        palette36.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette36.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette36.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_34.setPalette(palette36)
        self.label_34.setFont(font3)
        self.label_35 = QLabel(self.groupBox_7)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(30, 100, 231, 31))
        palette37 = QPalette()
        palette37.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette37.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette37.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_35.setPalette(palette37)
        self.label_35.setFont(font3)
        self.label_36 = QLabel(self.groupBox_7)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(30, 120, 231, 31))
        palette38 = QPalette()
        palette38.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette38.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette38.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_36.setPalette(palette38)
        self.label_36.setFont(font3)
        self.label_37 = QLabel(self.groupBox_7)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(30, 140, 231, 31))
        palette39 = QPalette()
        palette39.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette39.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette39.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_37.setPalette(palette39)
        self.label_37.setFont(font3)
        self.label_38 = QLabel(self.groupBox_7)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(30, 160, 231, 31))
        palette40 = QPalette()
        palette40.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette40.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette40.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_38.setPalette(palette40)
        self.label_38.setFont(font3)
        self.label_39 = QLabel(self.groupBox_7)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(30, 200, 301, 31))
        palette41 = QPalette()
        palette41.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette41.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette41.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_39.setPalette(palette41)
        self.label_39.setFont(font3)
        self.label_40 = QLabel(self.groupBox_7)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(30, 180, 231, 31))
        palette42 = QPalette()
        palette42.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette42.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette42.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_40.setPalette(palette42)
        self.label_40.setFont(font3)
        self.label_41 = QLabel(self.groupBox_7)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(30, 220, 301, 31))
        palette43 = QPalette()
        palette43.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette43.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette43.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_41.setPalette(palette43)
        self.label_41.setFont(font3)
        self.label_9 = QLabel(RoomInfo)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(100, 310, 171, 16))
        palette44 = QPalette()
        palette44.setBrush(QPalette.Active, QPalette.WindowText, brush14)
        palette44.setBrush(QPalette.Inactive, QPalette.WindowText, brush14)
        palette44.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_9.setPalette(palette44)
        font6 = QFont()
        font6.setPointSize(9)
        font6.setBold(False)
        font6.setWeight(50)
        self.label_9.setFont(font6)
        self.label_42 = QLabel(RoomInfo)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(100, 570, 171, 16))
        palette45 = QPalette()
        palette45.setBrush(QPalette.Active, QPalette.WindowText, brush14)
        palette45.setBrush(QPalette.Inactive, QPalette.WindowText, brush14)
        palette45.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_42.setPalette(palette45)
        self.label_42.setFont(font6)
        self.label_43 = QLabel(RoomInfo)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(750, 310, 171, 16))
        palette46 = QPalette()
        palette46.setBrush(QPalette.Active, QPalette.WindowText, brush14)
        palette46.setBrush(QPalette.Inactive, QPalette.WindowText, brush14)
        palette46.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_43.setPalette(palette46)
        self.label_43.setFont(font6)
        self.label_44 = QLabel(RoomInfo)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(750, 580, 171, 16))
        palette47 = QPalette()
        palette47.setBrush(QPalette.Active, QPalette.WindowText, brush14)
        palette47.setBrush(QPalette.Inactive, QPalette.WindowText, brush14)
        palette47.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        self.label_44.setPalette(palette47)
        self.label_44.setFont(font6)
        self.label_5.raise_()
        self.label_7.raise_()
        self.buttonBox.raise_()
        self.label_2.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.label_10.raise_()
        self.groupBox_4.raise_()
        self.groupBox_6.raise_()
        self.groupBox_7.raise_()
        self.label_9.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.label_44.raise_()

        self.retranslateUi(RoomInfo)
        # self.buttonBox.accepted.connect(RoomInfo.accept)
        # self.buttonBox.rejected.connect(RoomInfo.reject)

        QMetaObject.connectSlotsByName(RoomInfo)
    # setupUi

    def retranslateUi(self, RoomInfo):
        RoomInfo.setWindowTitle(QCoreApplication.translate("RoomInfo", u"RoomInfo", None))
        self.label_2.setText(QCoreApplication.translate("RoomInfo", u"R  o  o  m     I  n  f  o  r  m  a  t  i  o  n", None))
        self.groupBox.setTitle(QCoreApplication.translate("RoomInfo", u"ROOM A - STANDARD NON - AC ", None))
        self.label_3.setText(QCoreApplication.translate("RoomInfo", u"* ROOM INCLUSIONS *", None))
        self.label_11.setText(QCoreApplication.translate("RoomInfo", u"- 1 Double Bed", None))
        self.label_12.setText(QCoreApplication.translate("RoomInfo", u"- Telivision", None))
        self.label_13.setText(QCoreApplication.translate("RoomInfo", u"- Telephone", None))
        self.label_14.setText(QCoreApplication.translate("RoomInfo", u"- Double - Door Cupboard", None))
        self.label_15.setText(QCoreApplication.translate("RoomInfo", u"- 1 Coffee Table with 2 sofa", None))
        self.label_16.setText(QCoreApplication.translate("RoomInfo", u"-  Balcony", None))
        self.label_17.setText(QCoreApplication.translate("RoomInfo", u"-  Attached Washroom with Hot / Cold Water", None))
        self.label.setText(QCoreApplication.translate("RoomInfo", u"H  O  T  E  L    D  E  L    L  U  N  A", None))
        self.label_5.setText("")
        self.label_7.setText("")
        self.label_10.setText(QCoreApplication.translate("RoomInfo", u"A   P L A C E   L I K E    H O M E", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("RoomInfo", u"ROOM B - STANDARD AC", None))
        self.label_4.setText(QCoreApplication.translate("RoomInfo", u"* ROOM INCLUSIONS *", None))
        self.label_18.setText(QCoreApplication.translate("RoomInfo", u"- 1 Double Bed + 1 Single Bed", None))
        self.label_19.setText(QCoreApplication.translate("RoomInfo", u"- Telivision", None))
        self.label_20.setText(QCoreApplication.translate("RoomInfo", u"- Telephone", None))
        self.label_21.setText(QCoreApplication.translate("RoomInfo", u"- Triple - Door Cupboard", None))
        self.label_22.setText(QCoreApplication.translate("RoomInfo", u"- 1 Coffee Table with 2 sofa", None))
        self.label_23.setText(QCoreApplication.translate("RoomInfo", u"-  Balcony", None))
        self.label_24.setText(QCoreApplication.translate("RoomInfo", u"-  Attached Washroom with Hot / Cold Water", None))
        self.label_25.setText(QCoreApplication.translate("RoomInfo", u"-  Window / Split AC", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("RoomInfo", u"ROOM C - 3 BED NON - AC", None))
        self.label_6.setText(QCoreApplication.translate("RoomInfo", u"* ROOM INCLUSIONS *", None))
        self.label_26.setText(QCoreApplication.translate("RoomInfo", u"- 1 Double Bed + 1 Single Bed", None))
        self.label_27.setText(QCoreApplication.translate("RoomInfo", u"- Telivision", None))
        self.label_28.setText(QCoreApplication.translate("RoomInfo", u"- Telephone", None))
        self.label_29.setText(QCoreApplication.translate("RoomInfo", u"- Triple - Door Cupboard", None))
        self.label_30.setText(QCoreApplication.translate("RoomInfo", u"- 1 Coffee Table with 2 sofa", None))
        self.label_31.setText(QCoreApplication.translate("RoomInfo", u"-  Balcony", None))
        self.label_32.setText(QCoreApplication.translate("RoomInfo", u"-  Attached Washroom with Hot / Cold Water", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("RoomInfo", u"ROOM D - 3 BED AC", None))
        self.label_8.setText(QCoreApplication.translate("RoomInfo", u"* ROOM INCLUSIONS *", None))
        self.label_33.setText(QCoreApplication.translate("RoomInfo", u"- 1 Double Bed + 1 Single Bed", None))
        self.label_34.setText(QCoreApplication.translate("RoomInfo", u"- Telivision", None))
        self.label_35.setText(QCoreApplication.translate("RoomInfo", u"- Telephone", None))
        self.label_36.setText(QCoreApplication.translate("RoomInfo", u"- Triple - Door Cupboard", None))
        self.label_37.setText(QCoreApplication.translate("RoomInfo", u"- 1 Coffee Table with 2 sofa", None))
        self.label_38.setText(QCoreApplication.translate("RoomInfo", u"-  Balcony", None))
        self.label_39.setText(QCoreApplication.translate("RoomInfo", u"-  Attached Washroom with Hot / Cold Water", None))
        self.label_40.setText(QCoreApplication.translate("RoomInfo", u"-  1 Side Table", None))
        self.label_41.setText(QCoreApplication.translate("RoomInfo", u"-  Window / Split AC", None))
        self.label_9.setText(QCoreApplication.translate("RoomInfo", u"[ PHP 3,500 / PAX ]", None))
        self.label_42.setText(QCoreApplication.translate("RoomInfo", u"[ PHP 4,000 / PAX ]", None))
        self.label_43.setText(QCoreApplication.translate("RoomInfo", u"[ PHP 4,500 / PAX ]", None))
        self.label_44.setText(QCoreApplication.translate("RoomInfo", u"[ PHP 5,000 / PAX ]", None))
    # retranslateUi

